### ISSUE TITLE
Authors

### ISSUE THREAD

**Issue by sboerrigter** [trendwerk/trendpress#115]
Hi,

To create multi language websites we use WordPress Multisite. This works good for regular posts, pages and CPT's, but not for authors. The author settings are global settings, so the bio and other settings are the same aan all websites. Is there a way to fix this, or should we not use the author information anymore on WordPress multisite?

Using WP authors have some other disadvantages like: #111 an #112. Maybe we should extend this with a CPT or something like on the new Trendwerk website to get rid of all these problems. What do you guys think?

**Comment by haroldangenent** [comment]
My recommendations about enriched users:
- Don't create a plugin for this
- Use the power of post types to enrich users whenever (and however) we need it
- Connect a post type and users by using Posts 2 Posts or just WordPress' own 'author' options

For `trendpress`:
- Remove `page-authors.php`. I never use it (in fact, I have to manually remove it every time I use `trendpress`) and it's easy to build.
- Remove `partials/author.php` and stop showing an author below a post by default.
- Remove `assets/class-tp-users.php`.

We still use the latter two sometimes, but **not on every website by far**. They could be version controlled, so we can easily use them.

**Comment by sboerrigter** [comment]
Ok

**Comment by luukdv** [comment]
Sounds good, but isn't it questionable to use features of a third-party plugin in this new plugin? Or do you mean taking some of the functionalities and integrating them in our own plugin?

**Comment by haroldangenent** [comment]
> - Don't create a plugin for this

@luukdv There won't be a plugin for that :-) 

Was specifically wondering about the trendpress part (two latter bulletpoints) - should we keep this code (under version control somewhere)?

**Comment by luukdv** [comment]
Read the whole thing from the beginning, but not thorougly enough it seems. ;)

About the mentioned points, I think there's three options:

1. Stash the code in internal snippets (no version control)
2. Create some gists
3. Create a repository with some code parts

I think gists is the way to go. @haroldangenent What about you?

**Comment by haroldangenent** [comment]
I agree.

**Comment by haroldangenent** [comment]
Gists:
- [Author card](https://gist.github.com/haroldangenent/2f3015beebbc9e99ac63)
- [User settings](https://gist.github.com/haroldangenent/2c50be2976af0a460cc6)

Done:
- Moved `partials/authors.php` to gists and removed references to it
- Removed `page-authors.php`
- Moved `class-tp-users.php` to gist

To be done:
- Remove CSS for this partial (#387)
