### ISSUE TITLE
Line-height variable

### ISSUE THREAD

**Issue by gewoonderrik** [trendwerk/trendpress#116]
We should consider adding an line-height variable. It should come in handy in quite a few situations. For example:

It can be used throughout the typography. For instance, @Pjotter often uses 24px as a line-height for his typography. This is a pretty good number, because we can easily divide and multiply it to even numbers. If we set the @line-height variable to 24px we can use it on all the typographic elements, and add a `margin-bottom: @line-height;` as well. This will result in a better vertical balance. On elements that need less margin or line-height we can divide @line-height by two. 

We can use it on our grid. Maybe divide it by two so it evens out. Like this:
 `.threecol { margin: @line-height / 2 10px; }` which would result in `.threecol { margin: 12px 10px; }` This will result in an even better vertical balance. 

It can even be used for heights (`min-height` of course) to insure a height thats consistent with the vertical balance.

What do you guys think?

**Comment by gewoonderrik** [comment]
The variable is used throughout the framework these days. I think its safe to close this issue.

**Comment by haroldangenent** [comment]
It doesn't seem to be defined in `_variables.scss`. Could you explain a bit more about this? It's a while ago.

**Comment by gewoonderrik** [comment]
I've moved the line-height variable to `_variables.scss`. Don't know why I've placed the variable in `_typopgraphy.scss` in the first place. It clearly does not belong there. Feel free to close this if you want now that the variable has been moved to the right place.
