### ISSUE TITLE
We should think about adding Compass

### ISSUE THREAD

**Issue by gewoonderrik** [trendwerk/trendpress#216]
I'll do some further research for this matter. :tophat:

**Comment by gewoonderrik** [comment]
I'm not so sure about this these days. Even though Compass has some really nice features, I don't seem to miss them at all. Have a look at [this](http://www.sitepoint.com/dont-use-compass-anymore/) article for some more reasons why we maybe shouldn't use it.

**Comment by haroldangenent** [comment]
But there are some great things that might help us as well, right? [Spriting](http://compass-style.org/help/tutorials/spriting/), for example.

**Comment by luukdv** [comment]
Shall we move this one to our workflow topic on Basecamp and close it here?

**Comment by haroldangenent** [comment]
Yes.
