### ISSUE TITLE
Alignment social share buttons & tags isn't right

### ISSUE THREAD

**Issue by sboerrigter** [trendwerk/trendpress#256]
Please take a good look at the wireframes.

![screen shot 2014-07-11 at 13 49 16](https://cloud.githubusercontent.com/assets/786875/3552082/7d9ff4ea-08f1-11e4-846d-b54bbcc220c3.png)

**Comment by gewoonderrik** [comment]
I've had another look at this. The alignment issues have been fixed.
![screen shot 2015-02-17 at 21 59 23](https://cloud.githubusercontent.com/assets/1583229/6237134/95d1098e-b6f0-11e4-9d6f-d30104ad6594.png)
