### ISSUE TITLE
Gallery images get enlarged in the editor

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#281]
![schermafbeelding 2014-07-11 om 15 02 04](https://cloud.githubusercontent.com/assets/1481468/3552730/96031f3a-08fb-11e4-9a5c-d515028fc3c1.png)

**Comment by gewoonderrik** [comment]
Fixed this by setting the `.gallery-item` style to auto. This overwrites some CSS in the core WordPress files which caused the error.
![screenshot 2015-03-20 15 27 26](https://cloud.githubusercontent.com/assets/1583229/6753367/ab4477d2-cf15-11e4-835a-676d048f3de4.png)
