### ISSUE TITLE
Too little room between forms and share buttons

### ISSUE THREAD

**Issue by sboerrigter** [trendwerk/trendpress#298]
If yo place a form on a sinle post

![screen shot 2014-08-08 at 18 25 28](https://cloud.githubusercontent.com/assets/786875/3859445/afbf01fe-1f18-11e4-9b54-a89ab4149a43.png)

**Comment by gewoonderrik** [comment]
I've added a margin bottom to our Gravity Forms wrapper element which fixed the bug.
