### ISSUE TITLE
Theme wrapper

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#308]
Our typical template file looks like this:

```
<section id="main" class="container">

	<div class="container-inner">

		<aside>
			<?php dynamic_sidebar( 'page' ); ?>
		</aside>
		
		<article id="content">
		
			//Specific template code
			
		</article>

	</div>
	
</section>
```

According the [DRY](http://en.wikipedia.org/wiki/Don't_repeat_yourself) principle, we should not repeat ourselves. Maybe we should use a theme wrapper.

More about theme wrappers:
http://scribu.net/wordpress/theme-wrappers.html
http://roots.io/an-introduction-to-the-roots-theme-wrapper/

**Comment by haroldangenent** [comment]
Did some reading. I think we should use this. Any objections?

**Comment by luukdv** [comment]
No objections, as long as you think we're not overcomplicating things (we usually don't have *that* many template files).

**Comment by haroldangenent** [comment]
We don't need this now that we use Twig. Twig's extension method is super powerful.
