### ISSUE TITLE
Front-end JS dependencies

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#313]
Right now we don't use a dependency manager for front-end dependencies. The source is simply included within our repository. This makes repo's heavier than they should be.

[Bower](http://bower.io) seems the perfect solution to our problems. So far it seems like this has become the de facto standard.

**Comment by luukdv** [comment]
Shall we move this one to our workflow topic on Basecamp and close it here?

**Comment by haroldangenent** [comment]
I agree. We could create an issue when we want to incorporate this in TrendPress.

**Comment by haroldangenent** [comment]
Reopening this, this should be implemented.

**Comment by luukdv** [comment]
@gewoonderrik what we were talking about: https://www.npmjs.com/package/gulp-concat-vendor

**Comment by haroldangenent** [comment]
Please review #515.

**Comment by haroldangenent** [comment]
Don't forgot to edit https://github.com/trendwerk/trendpress/wiki/Development-tools.
