### ISSUE TITLE
Contact information: Maybe it should be a plugin

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#315]
Since the WP Settings API is really extendable, maybe this should be a plugin.

Especially when the dependencies of this data (widgets) would move to a better place.

**Comment by luukdv** [comment]
Agreed. My vote goes to bundling this stuff together in one plugin since they're relatively small pieces and dependent on each other.

**Comment by haroldangenent** [comment]
Moved contact information, widget and social widget to https://github.com/trendwerk/contact.
