### ISSUE TITLE
Grunt doesn't compile the same

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#324]
Whenever I use Grunt, I see changes to commit. I get new lines for some files. For example, look at this commit:

https://github.com/trendwerk/trendpress/commit/8e442dd8314759dc32c79c19ef0049e29b129f8d

I had new lines in `editor.css` and `style.css`. This shouldn't happen.

**Comment by gewoonderrik** [comment]
@haroldangenent Might have something to do with unixNewlines option within `Gruntfile.js`. I've set the boolean to false. Can you have a look if the problem persists and maybe give me some steps on how to reproduce this?
