### ISSUE TITLE
Tabs render over the menu

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#325]
I'm not sure if this is a bug in the Tabs plugin or in TrendPress, but let me show you:

![schermafbeelding 2014-10-31 om 18 56 09](https://cloud.githubusercontent.com/assets/1481468/4866651/c515f218-612d-11e4-863c-0be215b4e4bf.png)

Could be more beautiful.

**Comment by gewoonderrik** [comment]
I've fixed the conflicting style in the tabs plug-in. This bug shouldn't occur anymore.
![screenshot 2015-03-20 14 29 48](https://cloud.githubusercontent.com/assets/1583229/6752332/d31d38f0-cf0d-11e4-8ab4-462363a358c5.png)
