### ISSUE TITLE
Rename assets/js to assets/coffee

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#334]
We've renamed our `assets/css` folder to `assets/sass` when we started using SASS. However, we didnt rename `assets/js` to `assets/coffee`. I think we should.

**Comment by gewoonderrik** [comment]
Sounds like a good plan. I'm all for semantics. @luukdv @sboerrigter how do you guys feel about this?

**Comment by luukdv** [comment]
We should draw a line between simplicity and going too far for semantics. Since CoffeeScript's tagline is "It's just JavaScript" and it's perfectly acceptable to write plain JS in a coffee file, I think we should leave it like this.

**Comment by haroldangenent** [comment]
Yeah, you're probably right. `wontfix` seems like the right thing to do.

**Comment by gewoonderrik** [comment]
Agreed. Let not fix this!
