### ISSUE TITLE
Remove (some) widgets

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#336]
We don't always need these widgets. Most of the time we only need two or three of them.

Maybe we could create a widget pack repository, or maybe separate repositories, where we could maintain these widgets.

Any ideas?

**Comment by haroldangenent** [comment]
Removed social widgets in https://github.com/trendwerk/trendpress/commit/ced5cf80b9ae3667d9846559ac9ad3677dbc3f6b.

Still to do:
- Post type posts
- Taxonomy terms

Open for debate:
- Contact (see #315)
- Social (see #315)
- Submenu (see #317)
- All the endlessly customizable widgets (title, image, content, telephone number, button)

**Comment by haroldangenent** [comment]
Moved the submenu widget to [it's own repository](https://github.com/trendwerk/widget-submenu).

**Comment by haroldangenent** [comment]
Moved post type posts to [it's own repository](https://github.com/trendwerk/widget-post-type-posts).

**Comment by haroldangenent** [comment]
Moved taxonomy terms to [it's own repository](https://github.com/trendwerk/widget-taxonomy-terms).

**Comment by haroldangenent** [comment]
Removed references to contact settings in https://github.com/trendwerk/trendpress/commit/0fb60937f8749deae9bc35ee3dc615b4a4b58684.

Telephone widget is broken as of now.

**Comment by haroldangenent** [comment]
Removed a load of stuff in https://github.com/trendwerk/trendpress/commit/b9ab32e87ff06e8b8e2dda8afd1055258441eeae.

Moved customizable widget to https://github.com/trendwerk/widget-customizable. Double-checking stuff and then closing this issue.

**Comment by haroldangenent** [comment]
I think this is ready for release. Could someone test this entire issue and #315?

**Comment by gewoonderrik** [comment]
Seems to work alright. There's still some code in `_widgets.scss` though. Maybe we should move the code to gist files. Should I make a separate issue for this?

**Comment by haroldangenent** [comment]
@gewoonderrik You can move it immediately if you'd like.
