### ISSUE TITLE
Change mixins without arguments to extends

### ISSUE THREAD

**Issue by gewoonderrik** [trendwerk/trendpress#342]
"My rule of thumb is: mixins without arguments smell. When the return value of your mixin is dependent on arguments you pass to it, it should generate different output with every use. For a mixin that returns the width based on a number of columns when using a grid based layout for instance, that makes complete sense." 

Source: http://www.thesassway.com/editorial/sass-doesnt-create-bad-code-bad-coders-do

We do have a couple of mixins without arguments. We should turn these in to [extends](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#extend) instead.

**Comment by gewoonderrik** [comment]
@haroldangenent As for you comment about `_parts.scss` there's already an issue concerning our SASS structure. See: https://github.com/trendwerk/trendpress/issues/347

I do agree with you, we could do with a better structure. I will do some further investigation.

**Comment by haroldangenent** [comment]
That issue is about the structure of the contents of the file. Created https://github.com/trendwerk/trendpress/issues/371
