### ISSUE TITLE
Add separate SASS file for vars

### ISSUE THREAD

**Issue by gewoonderrik** [trendwerk/trendpress#343]
Currently we have two places where we define the variables for our SASS. Editor.scss and style.scss. This means that there's two places where we have to change something. Maybe we should make a separate file for this so we don't have to change the variables twice.

**Comment by haroldangenent** [comment]
Is `_vars.scss` the best name for this file?

- WordPress uses `_variables.scss`
- `_definitions.scss` sounds logical too

**Comment by luukdv** [comment]
My vote goes to `_variables.scss`.
