### ISSUE TITLE
Remove vendor prefixes (and some mixins)

### ISSUE THREAD

**Issue by gewoonderrik** [trendwerk/trendpress#345]
Looks like some of our mixins are a bit outdated / unnecessary because of improved browser support for CSS3. 

Have a look at this specification: http://css3.bradshawenterprises.com/which-vendor-prefixes-are-needed/

According to this we can remove our `border-radius`, `border-radiuses` and `box-shadow` mixin and update others.

**Comment by gewoonderrik** [comment]
Found something called [autoprefixer](https://github.com/postcss/autoprefixer). It automatically adds the right prefixes and there's even a handy Grunt plug-in we could use. Maybe something we should investigate further?

**Comment by haroldangenent** [comment]
Looks good to me.

**Comment by haroldangenent** [comment]
Decided not to use autoprefixer, since it's just about a couple of prefixes.

**Comment by gewoonderrik** [comment]
Removed `animate-this`, `border-radius`, `border-radiusses`, `box-shadow` and `opacity`. @luukdv is going to have a look at the gradient mixins. The remaining mixins still need partial vendors. We should have another look at this issue in maybe a year or so.

**Comment by haroldangenent** [comment]
Could you also remove them from https://github.com/trendwerk/trendpress/wiki/Mixins?

**Comment by luukdv** [comment]
I think animate-this (Android 4.1-4.3), border-radiuses (Firefox 12, Safari 3) and opacity (IE8) shouldn't have been completely removed, since they still require some prefixes.

**Comment by gewoonderrik** [comment]
@luukdv I've re-added animate-this. There's only a really small percentage of people using Firefox 12 and below and Safari 3 and below. And I don't really care for IE8. How do you feel about this?

**Comment by gewoonderrik** [comment]
@haroldangenent Removed the mixins from the Wiki. We should probably add a page about the extends file now don't you think?

**Comment by luukdv** [comment]
@gewoonderrik You're right, outdated browsers = outdated effects. They're details after all.

**Comment by gewoonderrik** [comment]
@luukdv Agreed! :+1:
