### ISSUE TITLE
Use source maps

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#351]
What is this `sourceMappingURL` thing?

https://github.com/trendwerk/trendpress/blob/c5f1ce5b795f212b79259e82dceec250417ea592/assets/sass/output/admin.css#L35
https://github.com/trendwerk/trendpress/blob/c5f1ce5b795f212b79259e82dceec250417ea592/assets/sass/output/style.css#L4438
https://github.com/trendwerk/trendpress/blob/c5f1ce5b795f212b79259e82dceec250417ea592/assets/sass/output/editor.css#L2734

**Comment by gewoonderrik** [comment]
Closing this. Seems to work in Safari but I haven't got around testing it in Chrome Canary or other browsers.
