### ISSUE TITLE
Use the_archive_title()

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#353]
WordPress 4.1 has a few new template tags.

https://make.wordpress.org/core/2014/12/04/new-template-tags-in-4-1/

**Comment by haroldangenent** [comment]
Proposing changes as made in https://github.com/trendwerk/trendpress/commit/9c334f753ee1a6f88f94c37caf378b05f7dd5cb6. Please review.

**Comment by gewoonderrik** [comment]
Seems to work just fine. Haven't seen any weird titles or anything. I'm closing this!
