### ISSUE TITLE
Maybe use the_posts_pagination

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#354]
WordPress 4.1 has a few new template tags.

https://make.wordpress.org/core/2014/12/04/new-template-tags-in-4-1/

**Comment by haroldangenent** [comment]
I think we should use `the_posts_pagination`, but maybe someone else should look into this (from a front-end perspective).

**Comment by haroldangenent** [comment]
How do you feel about removing it out of this milestone? Since #450 will take some time to research.

**Comment by luukdv** [comment]
Fine by me.

**Comment by haroldangenent** [comment]
Wontfix this in favor of #450.
