### ISSUE TITLE
Title tag

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#356]
WordPress 4.1 introduces a new type of theme support: `add_theme_support( 'title-tag' )`. We should decide if we want to use it (yes we probably want to).

**Comment by haroldangenent** [comment]
Proposing changes in https://github.com/trendwerk/trendpress/commit/d6531aad195a5822e269bf6c856d13f243c01e5d. Please review.

**Comment by gewoonderrik** [comment]
Seems to work fine!
