### ISSUE TITLE
Remove topnav

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#357]
We don't always use this, maybe it would be an idea to just add it if necessary.

Furthermore, I personally like the simplicity without a top navigation better.

**Comment by haroldangenent** [comment]
Removed code in https://github.com/trendwerk/trendpress/commit/73d54f436c0bbcfa5333c0ce5b71f28daa7fb543.

@gewoonderrik Could you remove the styling as well?

**Comment by haroldangenent** [comment]
And the search box should probably be repositioned, since `#topnav` was removed.

**Comment by sboerrigter** [comment]
I removed the styling for topnav and re-possitioned the search box.
