### ISSUE TITLE
Single.php has an empty #pager div

### ISSUE THREAD

**Issue by gewoonderrik** [trendwerk/trendpress#367]
See line 24 of comments.php. If it's empty we should consider hiding it.

**Comment by haroldangenent** [comment]
Margin seems to be buggy after removing it.

![schermafbeelding 2015-02-20 om 15 09 13](https://cloud.githubusercontent.com/assets/1481468/6287536/89c53f88-b912-11e4-90e0-b3bfb08987e1.png)

**Comment by haroldangenent** [comment]
Now it seems to have double the amount of space _below_ the pagination.

![schermafbeelding 2015-02-20 om 15 50 38](https://cloud.githubusercontent.com/assets/1481468/6288308/47b6d7fe-b918-11e4-9c10-5052c15dc2d2.png)

**Comment by gewoonderrik** [comment]
@haroldangenent Can you have another look?
