### ISSUE TITLE
Remove #twttrHubFrameSecure

### ISSUE THREAD

**Issue by gewoonderrik** [trendwerk/trendpress#368]
See lines 31 to 38 of `misc.css`. To my knowledge these fixes are obsolete. @sboerrigter What do you reckon?

**Comment by haroldangenent** [comment]
@sboerrigter will check if this is still necessary.

**Comment by sboerrigter** [comment]
I removed this fixed without any problems (tested in firefox, safari, chrome). I guess Twitter or AddThis solved this issue.
