### ISSUE TITLE
Add social media colours as SASS vars

### ISSUE THREAD

**Issue by gewoonderrik** [trendwerk/trendpress#369]
We use them on multiple occasions. Might as well add them as SASS vars in `style.scss` and `editor.scss` because that way we don't have to look them up each time we use them within our projects.

**Comment by haroldangenent** [comment]
Just one question; on what occasions should they be used twice in a single project?

**Comment by luukdv** [comment]
Below blogposts and sometimes on author archives/singles?

**Comment by haroldangenent** [comment]
What I meant was: when should the colors be used twice in the source? Wouldn't it make more sense to create one class for these social links (instead of two different ones)?
