### ISSUE TITLE
Can we make it so that the "extra" tool icons are alway visible?

### ISSUE THREAD

**Issue by Pjotter** [trendwerk/trendpress#375]
Or at least make it so that the style dropdown is always visible? Makes it a bit user friendly imho.

![schermafbeelding 2015-02-23 om 11 28 58](https://cloud.githubusercontent.com/assets/1845626/6326181/4f2f3dda-bb4f-11e4-82db-1f47ed1521d3.png)

**Comment by haroldangenent** [comment]
As far as I know, the image below shows our default editor (in `trendpress`). Always open.

![schermafbeelding 2015-02-23 om 15 43 45](https://cloud.githubusercontent.com/assets/1481468/6329677/da7d84d2-bb72-11e4-8545-f81723ab0dc8.png)

**Comment by Pjotter** [comment]
Than Betonrestore needs a TP updaten
