### ISSUE TITLE
Added newline in SASS indentation

### ISSUE THREAD

**Issue by luukdv** [trendwerk/trendpress#377]
Right now, we add an extra line every time we indent classes in SASS.

![sass](https://cloud.githubusercontent.com/assets/5585947/6748109/3f5b1144-cee2-11e4-9ba6-6664ad0dba9d.png)

This causes bigger, harder to read files, doesn't work well with Sublime (indentation lines don't align) and isn't following WordPress standards. I think we should remove them.

**Comment by haroldangenent** [comment]
Remove all new lines before and after a nested declaration. For example, line 86 and 97 should be removed in the case of `_forms.scss`.

Improve lines 68 - 78 as well for `_forms.css`.
