### ISSUE TITLE
To bubble or not to bubble

### ISSUE THREAD

**Issue by luukdv** [trendwerk/trendpress#378]
Right now, most of our responsive styling is located in the responsive stylesheet. In some places, bubbling is used. When we work on projects it's the same, there doesn't seem to be a default way of approach. Should we agree on this? My vote goes to bubbling.

Pro's:
- No need to indent all the ID's and classes again;
- All styling for one element is packed together in one place;
- When there are 'special' media query breakpoints (like 389px, 471px, 544px instead of the usual 980px, 640px), you don't have to add a whole new repetitive media query - similar to the first point
- Less lines of SASS in total

Cons:
- Individual files become bigger (solvable by breaking down our SASS files even more if needed)
- Files are less structured and scannable for the eye

What is everyone's opinion on this?

**Comment by haroldangenent** [comment]
@luukdv will research what this does for file size.

**Comment by luukdv** [comment]
Test:

Removed 121 lines from `_responsive.scss` and bubbled these with media queries below all the different selectors.
Output before: 86.958 KB (3901 lines)
Output after: 87.307 KB (3903 lines)

I think the impact on file size is reasonable. Besides, if we really think this is better (I do), we shouldn't refrain from this because of a slight size increase.

**Comment by haroldangenent** [comment]
I agree. Let's bubble.

**Comment by luukdv** [comment]
@gewoonderrik?

**Comment by gewoonderrik** [comment]
Agreed! :octocat:

**Comment by luukdv** [comment]
We're bubblin'.

**Comment by luukdv** [comment]
Final increase: 1.75KB

**Comment by gewoonderrik** [comment]
@luukdv Cool! Responsive seems to work alright. I think we can close this one.
