### ISSUE TITLE
Selection doesn't work by default

### ISSUE THREAD

**Issue by luukdv** [trendwerk/trendpress#379]
```
::-moz-selection,
::selection {
	background-color: $primary-color;
	color: #FFF;
}
```

This doesn't work since it's grouped together, we should separate the selectors. Or, we can remove this feature altogether and revert to the default browser styling for selected text.

**Comment by haroldangenent** [comment]
Let's remove this.

**Comment by luukdv** [comment]
This has reappeared, we should remove it again.

**Comment by haroldangenent** [comment]
Please review.

**Comment by luukdv** [comment]
Done
