### ISSUE TITLE
Desktop first framework

### ISSUE THREAD

**Issue by luukdv** [trendwerk/trendpress#380]
Right now, all the styling is based on a desktop first approach. If we change this, all the default styling is specifically for mobile. Using media queries we could extend this towards desktop. Benefit: we *only* use what's absolute necessary on mobile, the platform with limited resources and data. Working our way up to bigger screen sizes, features (and the associated styling) can be added.

What are the opinions on this?

**Comment by haroldangenent** [comment]
@luukdv will implement this.

**Comment by haroldangenent** [comment]
Found some bugs:

![schermafbeelding 2015-04-17 om 14 48 26](https://cloud.githubusercontent.com/assets/1481468/7202252/e2162768-e510-11e4-9a97-8f4fe8bd9838.png)
![schermafbeelding 2015-04-17 om 14 48 32](https://cloud.githubusercontent.com/assets/1481468/7202251/e21093ca-e510-11e4-8f6b-99b8e2c7f2b6.png)

**Comment by luukdv** [comment]
Thanks, will fix.

**Comment by haroldangenent** [comment]
**Post meta not very beautiful below centered title**

![schermafbeelding 2015-04-17 om 14 50 45](https://cloud.githubusercontent.com/assets/1481468/7202290/3414bd04-e511-11e4-940c-b2f692652549.png)

**Comment by luukdv** [comment]
Fixed them. Also the sticky one, since it would take more time to create a new issue

**Comment by haroldangenent** [comment]
@luukdv How would centering the post meta look?

**Comment by luukdv** [comment]
Better. Changed it
