### ISSUE TITLE
Column approach

### ISSUE THREAD

**Issue by luukdv** [trendwerk/trendpress#381]
Right now we use all these mixins for columns with specifically specified widths, which we include in some places. To me, this seems outdated. I think we should only styling where necessary.

Example: right now, we specify a column for an element, so the width is set to 460px for example. In most cases the element is smaller, and there's an unnecessary width declaration to force this column approach.

For me, it would be more logical to delete all this stuff. If an element should be on the left, we float it left. If it should be on the right, we float it right. If it should have a specific width, we add a width declaration.

**Comment by haroldangenent** [comment]
@gewoonderrik will think about this.

**Comment by haroldangenent** [comment]
@gewoonderrik Have you though about this?
