### ISSUE TITLE
Linting for CoffeeScript files

### ISSUE THREAD

**Issue by gewoonderrik** [trendwerk/trendpress#385]
>Linting is the process of running a program that will analyse code for potential errors. See lint on > wikipedia: lint was the name originally given to a particular program that flagged some suspicious and non-portable constructs (likely to be bugs) in C language source code

Source: Stackoverflow (http://stackoverflow.com/questions/8503559/what-is-linting)

We could start using Grunt plug-ins for SASS and CoffeeScript coding. This will help us write better code.

**Comment by gewoonderrik** [comment]
Coffee and SASS linting has been added. Validated the coffee script files. SASS is causing quite a few lint messages. We should have a look at these.

**Comment by haroldangenent** [comment]
@gewoonderrik is reversing this for now, we need more time to extensively test this.

**Comment by haroldangenent** [comment]
Closing this, since CoffeeScript works fine. See https://github.com/trendwerk/trendpress/issues/389 for SASS lint.
