### ISSUE TITLE
Apply the 'Inception rule' when it comes to nesting

### ISSUE THREAD

**Issue by gewoonderrik** [trendwerk/trendpress#386]
> To prevent you from falling into this nightmare, I created a simple rule. Until now, this rule has remained unwritten, but many followed. The Inception Rule: don’t go more than four levels deep. This basically means that you shouldn't be too specific or mimicking the DOM at any point. If you find yourself more than four levels deep, that's a red flag. Of course there are times when you'll be forced to go there, but it's not something you should be doing too much.

Source: [The Sass Way](http://thesassway.com/beginner/the-inception-rule)

Maybe we should have a look at our `.scss` files to see if we can apply this rule to reduce the size of our styles.

**Comment by luukdv** [comment]
Applied this, except for a few instances. The main menu has been left untouched for example, since it's really helpful for visualization.
