### ISSUE TITLE
Remove most CSS comments

### ISSUE THREAD

**Issue by luukdv** [trendwerk/trendpress#388]
```
// sub-header

#sub-header {
}

// main

#main {

     // content

     #content {
     }
}

// footer

#footer {
}
```

Right now, the styling looks like this. Since CSS is a markup language the declarations are self-explanatory, so my vote goes to removing these comments.

Note: I'm not against comments like `// if item has children, show indicator`, explanations for unclear things are perfectly valid.

**Comment by gewoonderrik** [comment]
Fine by me!

**Comment by haroldangenent** [comment]
Agreed.

**Comment by gewoonderrik** [comment]
Maybe we should use silent comment instead of regular ones. The regular comments are included in the compiles. Thoughts?

**Comment by gewoonderrik** [comment]
@luukdv I'm closing this and making a new issue.
