### ISSUE TITLE
Contact widget width

### ISSUE THREAD

**Issue by luukdv** [trendwerk/trendpress#391]
The contact widget has a fixed width for labels (90px), but this is too small for some information.

![schermafbeelding 2015-03-20 om 17 37 21](https://cloud.githubusercontent.com/assets/5585947/6756138/21b52d46-cf28-11e4-9bc2-5bdfa6fe6bcd.png)

**Comment by haroldangenent** [comment]
Simply made it wider.

**Comment by haroldangenent** [comment]
Actually, this code doesn't below in this repo anymore. After testing, it should be removed: https://github.com/trendwerk/trendpress/issues/390.

Added #390 to this milestone.
