### ISSUE TITLE
Gallery images don't have the right margin

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#394]
This happens when I set 3 columns in the editor. It should:

- Actually display 3 columns ór
- Have correct margin in any case

I'm in favor of the first, to fully support WordPress.

![schermafbeelding 2015-03-20 om 17 39 24](https://cloud.githubusercontent.com/assets/1481468/6756192/7d1cfee8-cf28-11e4-85d8-2a2bf4f51893.png)

**Comment by gewoonderrik** [comment]
Should work now. See screenshots. Can someone have look?
![screenshot 2015-04-17 13 16 20](https://cloud.githubusercontent.com/assets/1583229/7201125/31e63c4a-e504-11e4-98e7-78fc0d7fa4bb.png)
![screenshot 2015-04-17 13 16 14](https://cloud.githubusercontent.com/assets/1583229/7201124/31e321cc-e504-11e4-8c4b-f7fd09d7d19a.png)

**Comment by haroldangenent** [comment]
Works great, thanks.
