### ISSUE TITLE
Mobile menu styling

### ISSUE THREAD

**Issue by luukdv** [trendwerk/trendpress#396]
Default styling for the mobile menu could be improved.

![schermafbeelding 2015-03-20 om 17 46 00](https://cloud.githubusercontent.com/assets/5585947/6756283/01f8a90a-cf29-11e4-8f04-5d9ba523a076.png)

**Comment by haroldangenent** [comment]
@gewoonderrik Some feedback:

- Maybe the hit box for a link could be the full width of the menu? Makes it easier to click;
- The links should have active states to indicate where you are now;
- The links could have a bit more padding, my finger currently overlaps multiple links right now.

**Comment by gewoonderrik** [comment]
@haroldangenent Have another look if you will.

**Comment by haroldangenent** [comment]
Looks and feels great.
