### ISSUE TITLE
Remove sidebars

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#397]
They're old fashioned. For most themes these days, I immediately remove them.

I'm also in favor of removing the footer sidebar. It's cluttering.

**Comment by luukdv** [comment]
Agreed.

**Comment by haroldangenent** [comment]
@luukdv I have removed all sidebars from scripts and php files. Could you remove the styling and make the theme beautiful again without sidebars?

**Comment by luukdv** [comment]
Sure thing. What should we do with the default widget styling and `_widgets.scss`? Give 'em to @snokkie ?

**Comment by haroldangenent** [comment]
Yeah, great idea. :hatching_chick:

**Comment by luukdv** [comment]
Done.
