### ISSUE TITLE
Remove `assets/inc/class-tp-post-types.php`

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#398]
Could be created whenever we need it. Not sure what we should do about this:
```
remove_post_type_support( 'page', 'thumbnail' );
```

**Comment by haroldangenent** [comment]
Removed the file in https://github.com/trendwerk/trendpress/commit/ae5ef42d280485afc666b93bd52cf4f76906b39b.

Still not sure about the new placement of `remove_post_type_support( 'page', 'thumbnail' );` (`functions.php`). Please review.

**Comment by gewoonderrik** [comment]
Seems to work fine. Don't know of any better way of placing this. I'm closing.
