### ISSUE TITLE
Remove `assets/inc/class-tp-query.php`

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#399]
Could be created whenever it's needed. Empty files are good for nothing.

**Comment by luukdv** [comment]
Agreed.

**Comment by gewoonderrik** [comment]
OK!

**Comment by haroldangenent** [comment]
Removed in https://github.com/trendwerk/trendpress/commit/6eeb975ef7b9e9ae6d38adc96ff8d4b75de7cc73.

**Comment by gewoonderrik** [comment]
Removed indeed. No errors or issues thus far. I'm closing this.
