### ISSUE TITLE
Add organisation member for organizing gists

### ISSUE THREAD

**Issue by luukdv** [trendwerk/trendpress#400]
Right now, different people in this project (could) have TrendPress-related gists. We should have a central place for this, so there's no need to search when you need one. Since organisation gists aren't possible, we should add a virtual person to the project who stores all of them. Maybe our dinosaur?

**Comment by haroldangenent** [comment]
Done: https://gist.github.com/snokkie. Forked all known gists.

@luukdv Could you remove your original gists, so we won't be confused?

**Comment by luukdv** [comment]
Nice.

Done.
