### ISSUE TITLE
Editor: remove full screen button, add dfw

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#401]
Any objections?

https://en.support.wordpress.com/distraction-free-writing/

**Comment by haroldangenent** [comment]
Remark: we have to make sure `dwf` is only added when it was already in the toolbar.

**Comment by haroldangenent** [comment]
See https://github.com/trendwerk/trendpress/commit/4aceae63fb7ecdc0862943d875b545d3579994f3.

**Comment by gewoonderrik** [comment]
Seems to work. But it doesn't look right (see screenshot).
![screenshot 2015-04-17 13 28 23](https://cloud.githubusercontent.com/assets/1583229/7201296/e34523b0-e505-11e4-9af5-839ebd85628f.png)

**Comment by gewoonderrik** [comment]
The issue mentioned above doesn't happen in newer versions of WordPress (like 4.4.1). I'm closing this.
