### ISSUE TITLE
Use `the_archive_description`

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#405]
See https://developer.wordpress.org/reference/functions/the_archive_description/. We could use it like this to show category and tag descriptions by default:

```
the_archive_description( '<div class="taxonomy-description">', '</div>' );
```

**Comment by gewoonderrik** [comment]
@haroldangenent Where do you want to show these descriptions? Somewhere in `index.php`? I don't really see the benefit of this.

**Comment by haroldangenent** [comment]
Yeah, in `index.php`. It would show the tag and category description, which you can fill in in the back-end. Otherwise they would be good for nothing (as in previous WordPress versions).

**Comment by sboerrigter** [comment]
Looks like it is working properly.
