### ISSUE TITLE
Refactor search.php

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#406]

**Comment by haroldangenent** [comment]
Refactored in https://github.com/trendwerk/trendpress/commit/bb7de4756e1da7ef21229466bfdd893346199042.

**Comment by gewoonderrik** [comment]
Seems to work fine. I'd rather have the `<?php post_class(); ?>` removed from the articles. These classes always end up messing up the styles so I almost always remove them when I'm working on a project. How do you feel about this?

**Comment by luukdv** [comment]
Works good and the code looks clean. Agreed with @gewoonderrik about 'post_class()'.

**Comment by gewoonderrik** [comment]
Alright! I'm closing this one.
