### ISSUE TITLE
Main navigation styling

### ISSUE THREAD

**Issue by luukdv** [trendwerk/trendpress#408]
Right now there are about 190 lines of code for the main navigation, maybe it's possible to simplify this. Also the structure isn't really clear, we should restructure it from the ground up (mobile first of course) and remove unnecessary stuff.

**Comment by luukdv** [comment]
Looks good. A few issues:

- Not enough vertical space on mobile to tap on links
- Dropdown menu's are pretty wide (300px), I think they were smaller (260px)
- Z-index issue with dropdowns:
![screen shot 2015-05-15 at 16 31 13](https://cloud.githubusercontent.com/assets/5585947/7654795/e923ddf0-fb1f-11e4-8239-85c8ecff4b7d.png)

**Comment by sboerrigter** [comment]
* I changed the line-height on mobile devices
* Drop-downs are now 260px wide again
* Z-index issue with drop-downs is fixed
* Dropdown arrows are now visible

Can you take a look again?
