### ISSUE TITLE
Mobile header needs more spacing

### ISSUE THREAD

**Issue by gewoonderrik** [trendwerk/trendpress#409]
* Needs a little bit more spacing between the title and the description. 
* The line-height of the description is a bit big
* The spacing between the title and the top and the description and the bottom seems to be a bit small

![screenshot 2015-04-17 14 48 51](https://cloud.githubusercontent.com/assets/1583229/7202286/2d713a2c-e511-11e4-8bfb-f572d485b117.png)

**Comment by luukdv** [comment]
I don't think I changed anything about these margins/line-heights, should this be in 1.0.3?

**Comment by luukdv** [comment]
Waiting for verdict on #417.

**Comment by sboerrigter** [comment]
#417 is closed. This looks good, so I am closing this one as well.
