### ISSUE TITLE
Toggle switches don't have a active state

### ISSUE THREAD

**Issue by gewoonderrik** [trendwerk/trendpress#411]
Maybe we should remove the hover state (since that doesn't do anything on touch screens) and use it as an active state?

![screenshot 2015-04-17 14 58 08](https://cloud.githubusercontent.com/assets/1583229/7202380/10954082-e512-11e4-8fb3-d4d8cc7767b3.png)

**Comment by gewoonderrik** [comment]
Fixed this. Someone please review!

**Comment by haroldangenent** [comment]
Works like a charm.
