### ISSUE TITLE
Remove AddThis button from share.php

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#412]
The dropdown is too ugly.

I'm still in favor of removing all share buttons by default.

**Comment by luukdv** [comment]
Yes! I don't have any data to back this up, but my feeling says it's seldomly used anyway.

**Comment by haroldangenent** [comment]
We will remove AddThis entirely.

**Comment by sboerrigter** [comment]
Yay! It looks good. I'll close this.
