### ISSUE TITLE
Submenu has weird positioning

### ISSUE THREAD

**Issue by gewoonderrik** [trendwerk/trendpress#413]
![screenshot 2015-04-17 15 15 35](https://cloud.githubusercontent.com/assets/1583229/7202633/7ad8626a-e514-11e4-91ff-9e8dc9fc3cd3.png)

**Comment by luukdv** [comment]
@gewoonderrik could you have a look?

**Comment by gewoonderrik** [comment]
@luukdv Thanks for fixing this!
