### ISSUE TITLE
 Search field margin

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#414]
Margin top and bottom should be the same.

![schermafbeelding 2015-04-17 om 15 14 19](https://cloud.githubusercontent.com/assets/1481468/7202650/adc9d668-e514-11e4-9dea-01ba32d57587.png)

**Comment by luukdv** [comment]
@gewoonderrik do you have time to look at this? I haven't touched the margins on this.

**Comment by gewoonderrik** [comment]
@haroldangenent Fixed this. Please review! 

![screenshot 2015-04-17 15 17 18](https://cloud.githubusercontent.com/assets/1583229/7203768/6514edf0-e51d-11e4-8046-82f6c5635539.png)
