### ISSUE TITLE
Mobile: Slim down header

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#417]
The header is quite high. I would focus the mobile version purely around content. Possible improvements:
- Remove description
- Place search and menu icon on top left and top right (next to 'logo')

![schermafbeelding 2015-04-17 om 15 39 01](https://cloud.githubusercontent.com/assets/1481468/7203036/e721aea6-e517-11e4-83c3-21f48f58cbc5.png)

**Comment by gewoonderrik** [comment]
Good point. We almost never use the description anyway.

**Comment by haroldangenent** [comment]
Could do without the description and a bit cleaner. Waiting for #421.

**Comment by luukdv** [comment]
I'm in favor of removing the description. Who agrees?

**Comment by haroldangenent** [comment]
:+1:

**Comment by sboerrigter** [comment]
OK i'll take care of it

**Comment by sboerrigter** [comment]
Done. Needs testing.

**Comment by haroldangenent** [comment]
Looks great.
