### ISSUE TITLE
Mobile: Subheader

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#418]
- Vertical align of title + subtitle is off
- Description could have more line height

![schermafbeelding 2015-04-17 om 15 41 50](https://cloud.githubusercontent.com/assets/1481468/7203092/46171bd0-e518-11e4-9a2c-93685cbab789.png)

**Comment by luukdv** [comment]
Agreed, although I think this is an improvement (not a bug)

**Comment by haroldangenent** [comment]
Seems to work fine.
