### ISSUE TITLE
Submenu should clear when it doesn't fit on screen

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#420]
![schermafbeelding 2015-04-17 om 15 54 12](https://cloud.githubusercontent.com/assets/1481468/7203323/163f737e-e51a-11e4-9a70-4be2d497ef77.png)

**Comment by gewoonderrik** [comment]
Sub-menu's suck. Especially when there's a sub-sub menu and a sub-sub-sub menu. This is going to be a though nut to crack.

**Comment by luukdv** [comment]
Yup. Maybe we shouldn't put *too* much effort in beautifully supporting sub-sub-sub-sub menu's since it's a starter theme.

**Comment by haroldangenent** [comment]
It also happens on sub-submenu's, but I agree the code should be simple. Maybe just clear them or don't show them at all. Sub-submenu's (and deeper) are probably too complex for users anyway.

**Comment by sboerrigter** [comment]
I don't know how to fix this :-S.

**Comment by luukdv** [comment]
So this will be a wontfix?
