### ISSUE TITLE
Improve Gruntfile.js

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#423]
Could be shorter and use better coding standards.

**Comment by sboerrigter** [comment]
Sass compiling didn't seem to work. I have fixed this in https://github.com/trendwerk/trendpress/commit/5ea8af0718ad6816bd568d3939695682aefef41c. Is this okay?

**Comment by haroldangenent** [comment]
Fixed naming convention in https://github.com/trendwerk/trendpress/commit/d6f3788c7e5bec60f36d9435e46399d1398a8d1e. @sboerrigter please review again.

**Comment by sboerrigter** [comment]
Works
