### ISSUE TITLE
Remove #main `border-top`

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#427]
I'm not sure why #main has a `border-top` of one pixel. You can barely see it below the menu and it seems less clean.

**Comment by sboerrigter** [comment]
I have removed the border and gave the mobile header a dark background, so it contrasts with the content. What do you guys think?

**Comment by gewoonderrik** [comment]
I like it!

**Comment by haroldangenent** [comment]
Nice.
