### ISSUE TITLE
Lint files before compiling them

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#430]
We should probably lint files before compiling them with Grunt. Non-valid files still get compiled right now.

**Comment by sboerrigter** [comment]
I cannot reproduce this issue, but I edited the Gruntfile so the lint tasks are loaded before the compile tasks. Can you check if it works?

**Comment by haroldangenent** [comment]
Nope, doesn't work. Whenever I have an invalid coffee file (according to the linter), it still compiles.

**Comment by sboerrigter** [comment]
Sorry guys, I don't know enoug about linting and Grunt to fix this. Can somebody else take a look at this?

**Comment by haroldangenent** [comment]
Fixed in https://github.com/trendwerk/trendpress/commit/2db798719ab529f05c2d47ce363a15813a585e38. Please review.

**Comment by luukdv** [comment]
Tested, works good.
