### ISSUE TITLE
Don't use negative margins

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#433]
Examples:

https://github.com/trendwerk/trendpress/blob/master/assets/sass/_layout.scss#L102
https://github.com/trendwerk/trendpress/blob/master/assets/sass/_layout.scss#L108

**Comment by sboerrigter** [comment]
I agree with @luukdv that this is better for touch devices since the touch area is bigger. I vote for 'wont fix'. Do you guys agree?

**Comment by gewoonderrik** [comment]
Agreed!

**Comment by haroldangenent** [comment]
Yeah
