### ISSUE TITLE
Rename assets folders

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#434]
- `assets/coffee` :arrow_right: `assets/scripts`
- `assets/sass` :arrow_right: `assets/styles`

This would be a bit more semantic, since they can contain other scripts and styles as well (in the form of libraries).

And maybe:
- `assets/img` :arrow_right: `assets/images`
- `assets/lang` :arrow_right: `assets/languages`
- `assets/inc` :arrow_right: `assets/includes`

To keep things consistent.

**Comment by haroldangenent** [comment]
Please review.

**Comment by gewoonderrik** [comment]
Looks good to me. Haven't seen any `404` errors so I guess it's working fine.
