### ISSUE TITLE
Timber: Theme checker

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#439]
Since the Timber merge, TrendPress probably won't be able to get through the theme checker. Maybe check if we could make it pass.

**Comment by sboerrigter** [comment]
I have tested the theme with the theme checker and found the following issues:

* Grunt uses some PHP short tags (See #441)
* Setting a content width is mandatory (See #442)
* Some WordPress functions are mandatory   (See #443)
* Doctype not found (See #444)

I'll close this issue so we kan discuss the points above in the corresponding issues.
