### ISSUE TITLE
Gulp

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#440]
Use Gulp, because it has a prettier logo.

And it's cleaner, simpler and faster.

**Comment by gewoonderrik** [comment]
Alright. Note; we should implement Gulp before implementing Bower.

**Comment by haroldangenent** [comment]
I don't agree, we can implement them both whenever we feel like it (whatever is most important).

**Comment by luukdv** [comment]
I feel Bower has priority, since Grunt works okay.

**Comment by sboerrigter** [comment]
I agree with @haroldangenent. I don't like waiting.

**Comment by sboerrigter** [comment]
I just merged the Gulp branche. Can we close this issue?
