### ISSUE TITLE
Theme theck: Setting a content width is manditory

### ISSUE THREAD

**Issue by sboerrigter** [trendwerk/trendpress#442]
```if ( ! isset( $content_width ) ) $content_width = 900;```

**Comment by haroldangenent** [comment]
This was removed (by yourself) in https://github.com/trendwerk/trendpress/commit/2cea756d4fc7bf7b0d684ccbd0856644ac425d0e. We probably did this on purpose.

**Comment by haroldangenent** [comment]
Feel free to reopen if you feel differently.
