### ISSUE TITLE
Theme check: Doctype not found

### ISSUE THREAD

**Issue by sboerrigter** [trendwerk/trendpress#444]
Sould be something like this:

```<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"?>```

**Comment by gewoonderrik** [comment]
This is an XHTML doctype. We're using HTML5 so the doctype declaration should be `<!DOCTYPE html>` (which we're already using by the way). I guess this is a won't fix... right?

**Comment by luukdv** [comment]
Yes.
