### ISSUE TITLE
Remove //2

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#448]
This comment appears in several places. It doesn't do anything and should be removed. Marking this as bug because it annoys me too much.

https://github.com/trendwerk/trendpress/blob/master/assets/styles/_template.scss#L150

**Comment by gewoonderrik** [comment]
Look like this might have happened during a find and replace. The line-height variable should have been divided by two using the `/` instead there was another dash added somehow. The issue has been resolved.
