### ISSUE TITLE
Create menu helper class for Timber

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#449]
Right now there's a Timber helper function in `class-tp-menus.php` (function is named `timber()`), so Timber knows the menu's HTML. I've done this, so we could use `wp_nav_menu()` instead of using Timber's default menu (a loop).

Maybe this should be in a separate Helper class. This file can be used to add global helpers for Timber (filters and context definitition).

What do you guys think?

**Comment by haroldangenent** [comment]
Depends on #456.

**Comment by gewoonderrik** [comment]
Looks good!
