### ISSUE TITLE
Timber: tp_pagination

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#450]
I'd like to refrain from using `fn()` as much as possible. Maybe we should instantiate a variable that contains pagination.

Right now we are using a function that outputs HTML. We could also output this HTML using a Twig template. Another option would be to fill a variable with the HTML output we're using right now. I'm not sure what's the better option.

Would love to hear ideas.

**Comment by luukdv** [comment]
Related to https://github.com/trendwerk/trendpress/issues/354. I think it's best to use as many built-in options as well, so my vote goes to creating a twig template for this.

**Comment by gewoonderrik** [comment]
Sounds like a good plan to me. Let's use Twig!

**Comment by sboerrigter** [comment]
I don't know enough about this to give a solid opinion, so i'll trust you guys on this one.

**Comment by luukdv** [comment]
@haroldangenent do you feel like looking into this?

**Comment by haroldangenent** [comment]
@luukdv I'm not sure what you mean. Right now we're using built-in functions of WordPress itself, which output HTML. Are you saying we should write that HTML ourselves?

**Comment by luukdv** [comment]
What I mean is this (the way Timber uses it): https://github.com/jarednova/timber/wiki/Pagination, I thought that's what you were referring to.

**Comment by haroldangenent** [comment]
Was thinking of something like that, but I'm not sure if it works the same. For example, can we set the gap? And maximum amount of pages to show before show `...`?

Needs some research.

**Comment by luukdv** [comment]
Me neither, it definitely needs some research. If the stuff you're referring to is possible and works good, I think we should use it.

**Comment by gewoonderrik** [comment]
Looks good @haroldangenent. I'm closing this!
