### ISSUE TITLE
Remove front page (and the subheader variable)

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#451]
We could display this as a normal page. Front pages can be created on a per-project basis.

**Comment by luukdv** [comment]
Agreed, this is just to make our default theme pretty. Whenever we use TrendPress it's changed or removed anyway.

On the other hand, it makes our default theme pretty.

**Comment by haroldangenent** [comment]
It's actually also quite pretty without the front page :-)

**Comment by gewoonderrik** [comment]
Looks good to me @haroldangenent. I'm closing this issue.
