### ISSUE TITLE
Timber: the_post_thumbnail

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#453]
We could output the HTML ourselves and just fill in the source. For example:

```
<img src="{{post.thumbnail.src}}" />
```
or
```
<img src="{{post.thumbnail.src}}" alt="{{post.title}}" />
```

instead of

```
{{fn( 'the_post_thumbnail', 'medium' )}}
```

See https://github.com/Upstatement/timber-starter-theme/blob/master/views/tease-post.twig.

**Comment by gewoonderrik** [comment]
Seems to work allright. I'm closing the issue.
