### ISSUE TITLE
Timber: the_tags

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#454]
Instead of calling `fn()`, it could be done in a Twig-style template: https://github.com/jarednova/timber/wiki/TimberPost#terms

**Comment by gewoonderrik** [comment]
@haroldangenent Can you have a look?

**Comment by haroldangenent** [comment]
@gewoonderrik Looking good.

**Comment by haroldangenent** [comment]
The word "Tag" still shows when there are no tags.

**Comment by haroldangenent** [comment]
Please review.

**Comment by gewoonderrik** [comment]
Works!
