### ISSUE TITLE
Timber: Menus

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#456]
Right now this is done through a context helper and the `wp_nav_menu()` function. 

Could be done Timber style: https://github.com/Upstatement/timber-starter-theme/blob/master/views/base.twig#L16-33

Related: #449

**Comment by luukdv** [comment]
From what I've seen, I like the Timber style a lot since you have so much control over the output.

**Comment by gewoonderrik** [comment]
Works! It's a bit more code, but also more control overall. I'm closing this!
