### ISSUE TITLE
Timber: the_category

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#458]
`partials/post-meta.twig` contains a function call to `the_category`. We should look for alternatives.

**Comment by gewoonderrik** [comment]
Using Twig/Timber functionality now. Can someone please review?

**Comment by haroldangenent** [comment]
@gewoonderrik Doesn't seem really readable at this point. Especially this part seems off:

```
{% if loop.last == false %},{% endif %}
```

_Somehow, this line has a lot of whitespace behind it as well._

I feel like this should be better.

**Comment by haroldangenent** [comment]
Chose to only display the first category to make things simple by default. Please review.

**Comment by gewoonderrik** [comment]
Works!
