### ISSUE TITLE
Place /includes/ in ../lib/

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#459]
This means it will move from `assets/includes/` to `lib/`. This seems more semantical, since the PHP file are not assets (like styling and scripts).

An example of what I'm proposing can be found here: https://github.com/roots/sage.

**Comment by haroldangenent** [comment]
Suggested file tree:

- `lib/autoload.php`
- `lib/init.php` (contains everything currently in `functions.php`)
- `lib/editor.php`
- `lib/enqueue.php`
- `lib/media.php`
- `lib/menus.php`
- `lib/template-tags.php`

In specific websites, it could be extended by adding files or folders such as:

- `lib/widgets/`
- `lib/postmeta/`
- `lib/termmeta/`
- `lib/helpers/`

**Comment by haroldangenent** [comment]
Maybe not `/hooks/` because everything is probably connected to a WordPress hook. But I'd like to separate the symbols from the side-effects. So maybe:

- `lib/classes/*.php`
- `lib/classes/postmeta/*.php`
- `lib/autoload.php`
- `lib/init.php`

**Comment by sboerrigter** [comment]
We say: okay!

**Comment by gewoonderrik** [comment]
Works!
