### ISSUE TITLE
DB requests

### ISSUE THREAD

**Issue by luukdv** [trendwerk/trendpress#461]
Is it an idea to add some hardcoded stuff instead of `site.language_attributes` and `site.charset`? To avoid unnecessary DB traffic.

**Comment by haroldangenent** [comment]
These are set by Timber anyway, see [these lines of code](https://github.com/jarednova/timber/blob/master/lib/timber-site.php#L59-71) for more information.

WordPress caches a lot of this information (all autoloaded options in fact), so this probably doesn't cause DB traffic anyway. Take a look at a fresh TrendPress install, which causes only 15 queries to run on the front page.
