### ISSUE TITLE
PHP-CS

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#463]
As soon as #462 is completed, we should test and implement the PHP Coding Standards Fixer: https://www.npmjs.com/package/grunt-php-cs-fixer.

**Comment by sboerrigter** [comment]
Do we really want to fix this automatically? Maybe it is better to fix it manually, so we can learn to do it right the next time.

**Comment by haroldangenent** [comment]
Changed the name to `PHP-CS` to not include the fixer. I'll create a separate issue to research this, because this could save some time for easy fixes.
