### ISSUE TITLE
Twig coding standards

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#465]
http://twig.sensiolabs.org/doc/coding_standards.html

**Comment by sboerrigter** [comment]
Is there a linter for Twig coding standards?

**Comment by haroldangenent** [comment]
Can be tested according to the documentation above. There is not coding standards linter.

**Comment by gewoonderrik** [comment]
Had a look at the `.twig` files. Looks good! Haven't found any inconsistencies.
