### ISSUE TITLE
HTML coding standards

### ISSUE THREAD

**Issue by sboerrigter** [trendwerk/trendpress#470]
Maybe we should also use a coding standard for CoffeeScript. Some resources I found:

* https://google.github.io/styleguide/htmlcssguide.xml
* https://make.wordpress.org/core/handbook/coding-standards/html/
* http://www.w3schools.com/html/html5_syntax.asp
* https://validator.w3.org/
* http://codeguide.co/#html

**Comment by haroldangenent** [comment]
http://cssguidelin.es/#html

**Comment by sboerrigter** [comment]
I like the HTML coding standards on http://www.w3schools.com/html/html5_syntax.asp and http://codeguide.co/#html the most. Whay about you guys?

**Comment by haroldangenent** [comment]
I like [codeguide.co](http://codeguide.co/#html) the best, seems a bit more concise. Is there any way to automate this?

**Comment by luukdv** [comment]
Derrik will have a look at how we can improve things.

**Comment by haroldangenent** [comment]
As far as I can see, these are the actual issues:

- #645 
- #646
- #647
- #648
- #649
- #650

Any additions?

I suggest closing this issue in favor of those others.

**Comment by sboerrigter** [comment]
Agreed
