### ISSUE TITLE
PHP-CS Fixer

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#472]
Maybe auto-fix PSR issues.

**Comment by sboerrigter** [comment]
We are not sure about this, because then we don't learn anything.

**Comment by haroldangenent** [comment]
The pro is that all 'stupid' fixes can be done automatically. Maybe when you accidentally insert a trailing whitespace at the end of a line, or forgot a space or new line.

The con is that you don't learn about writing code properly and you don't get used to typing things right the first time. You just get a bit lazier. I'll close this for now, feel free to reopen.
