### ISSUE TITLE
Breakpoint manager

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#474]
This could be quite useful, since there are some basic points where most stuff breaks. This seems like a good modular approach: http://sass-guidelin.es/#breakpoint-manager.

**Comment by gewoonderrik** [comment]
The breakpoint manager has been implemented. Seems to work fine. Can someone please review?

**Comment by luukdv** [comment]
Looks good, works good. I like this.

**Comment by gewoonderrik** [comment]
Agreed!

**Comment by haroldangenent** [comment]
Why is the map defined like this:

```
$breakpoints: (
  'small':       (min-width: 421px),
  'medium':      (min-width: 641px),
  'large':       (min-width: 981px),
  'huge':        (min-width: 1161px),
);
```

This seems more readable and DRY:
```
$breakpoints: (
  'small': 421px,
  'medium': 641px,
  'large': 981px,
  'huge': 1161px,
);
```

**Comment by luukdv** [comment]
Tweaked the mixin a little so this is possible. Please review.
