### ISSUE TITLE
Remove <figure> around thumbnails

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#476]
We probably don't need it.

**Comment by gewoonderrik** [comment]
Removed `<figure>`. Added a class to the image so we can specifically target it. Can some review this?

**Comment by sboerrigter** [comment]
Do we really need to add the class `featured-image` or can we do without it?

Also, why not just `featured`? Maybe that's more semantical since the `<img>` tag already suggests it's an image.

**Comment by gewoonderrik** [comment]
Because just targeting the `img` will probably result in specificity issues. `.featured` isn't a good class name because then we have to target it like `img.featured` and using `.featured` in Sass isn't semantic either.

**Comment by luukdv** [comment]
`img` will also target images in the content, but I agree about using `.featured`. `img.featured` isn't necessary since there are no other elements on the page with the featured class.

**Comment by sboerrigter** [comment]
Ok, I am also in favor of using `.featured`

**Comment by gewoonderrik** [comment]
Changed the class name as requested. Can someone please review?
