### ISSUE TITLE
Remove main selector

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#477]
For example, in `_template.scss`, the content is selected as follows:

```
.single main #content {
```

`main` could (and should) be removed here to avoid specifity issues.

**Comment by sboerrigter** [comment]
We should wait until #479 is fixed.

**Comment by gewoonderrik** [comment]
The situation as described above doesn't exist in the OOCSS branche. Can someone please review?

**Comment by haroldangenent** [comment]
Looks good, will be closed automatically.
