### ISSUE TITLE
Remove section#content

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#478]
We only need all three wrappers when there's a sidebar. Our theme doesn't support sidebars.

Could easily be added when necessary, it's just in `base.twig`.

```<main>

	<div class="wrapper">
		
		<section id="content">

			{% block content %}
				{{__( 'No results found.', 'tp' )}}
			{% endblock %}
			
		</section>

	</div>
	
</main>```

**Comment by gewoonderrik** [comment]
`<section id="content">` has been removed. Updated the styling as wel. Can someone please review?

**Comment by sboerrigter** [comment]
There us still a CSS selector with `#content` in _templates.scss on line 112
