### ISSUE TITLE
Modular approach

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#479]
- [Separate structure and skin](https://github.com/stubbornella/oocss/wiki#separate-structure-and-skin)
- [Separate container and content](https://github.com/stubbornella/oocss/wiki#separate-container-and-content)

**Comment by sboerrigter** [comment]
@luukdv will talk ofzo. On monday

**Comment by haroldangenent** [comment]
OOCSS will be implemented for 1.1.0.

**Comment by haroldangenent** [comment]
By the way: This means a complete rewrite, taking into account the main principles of OOCSS:

- Separate structure from skin
- Separate container and content

**Comment by haroldangenent** [comment]
Please update https://github.com/trendwerk/trendpress/wiki/Mixins after fixing this.

**Comment by haroldangenent** [comment]
Soms remarks on `_functions.scss`:

- I wouldn't call the mixins by the name of functions. This is confusing, since functions are a thing;
- We could use some functions to simplify things;
- Commenting with `@section` and `@subsection` seems needless, let's simplify our comments and use SassDoc for re-usable lego's, functions and mixins;
- Some mixins can be removed, because they're not useful or needless because of autoprefixer.

**Comment by haroldangenent** [comment]
I'm really enthusiastic about this, thanks for your work @gewoonderrik and @luukdv! Did a small review, you'll find a better overview on the current situation below. A lot of things are questions, I hope one of you could answer these.

#### General
- [ ] My biggest remark: On a lot of occasions, structure and skin are not separated
- [ ] All strings (except valid CSS properties) should be wrapped in quotes

#### main.scss
- [ ] Inclusion order seems strange. Sometimes this is done alphabetically, but sometimes this is done logically. I'd prefer doing things logically, otherwise you'd have to include components before utils. _If_ done logically:
 - [ ] Include footer below header and main
 - [ ] Include main navigation below header

#### _functions.scss
- [ ] I wouldn't call the file with mixins by the name of functions. This is confusing, since functions are a thing
- [ ] Seperate this file anyway. Each mixin or function should have it's own file, especially when looking at SassDoc which we will implement soon.
- [ ] `border-radius` mixin can be removed, it's not useful anymore (since autoprefixer)
- [ ] Wouldn't it be better to create separate mixins for button types? Doesn't seem like the thing to use a parameter for.
- [ ] Why is there a `meta` mixin when it's only used once as implementation?
- [ ] How about a mixin for `display: block` with `margin-bottom` and `display: block` with `float: left`? Maybe even a structure like this (I'm not sure about this):
 - `block()`
 - `block-float()` (extends `block()`)
 - `block-margin()` (extends `block()`)
 - This could be further extended for site-specific things.
- [ ] The current `block()` mixin is too non-description. I'm not sure what it does and it doesn't even `display: block`
- [ ] Remove `gradient()`, it's not used and this is not intended as a library. [Fezcat](https://gist.github.com/fezcat) might be interested :-)
- [ ] Some mixins have `parenthesis()` and some don't. Should be consistent.
- [ ] Remove `placeholder()` in favor of style simplification. Current use is exactly the same on both occasions: `@include placeholder($text-color, $text-light);`. This should be default styling on the element level.
- [ ] Rename `remove-list-styles` to `list-style-none`. Most other mixins don't use nouns as actions.
- [ ] Remove `sprite()` (the images as well probably): It is not used and this is not intended as a library. They are site-specific things and should be implemented on a site-specific level. Of course, that implementation method should be efficient.

#### _helpers.scss
- [ ] This should not be in `utils/`. According to the guidelines used): 

> The utils/ folder gathers all Sass tools and helpers used across the project. Every global variable, function, mixin and placeholder should be put in here.

_(so only for Sass things, I'd recommend giving them their own file)_
- [ ] Actually, remove all helpers, since they are not in use anywhere at this moment (and probably not on a lot of other websites as well). If we need them, they should probably be a Sass mixin as well.

#### _typography.scss
- [ ] Separate this file in multiple files (maybe even folders), so the folder structure gives a better overview of the styles. For example, headings, links and lists could use their own file. I don't think there's such a thing as 'too many files' in this approach

#### _footer.scss
- [ ] Use the element `footer` as a selector, instead of a class. This is also done on `main` and there's only one footer by default. Maybe there should always be one footer each page.

#### _header.scss
- [ ] Use the element `header` as a selector, instead of a class. This is also done on `main` and there's only one header by default. Maybe there should always be one header each page.

#### _main.scss
- [ ] Why does the `main` element need it's own `.wrapper` styling?

#### _article.scss
- [ ] I'm not sure if `.hentry` is the right class. This would inherit the same styling to new post types and you'd have to change this file afterwards. How about `.type-post`?

#### _button.scss
- [ ] The argument for the secondary button, `secondary`, should be wrapped in quotes.

#### _comment-form.scss
- [ ] This file should be called `_comment-respond.scss`, since it contains that class and only that class.

#### _comments.scss
- [ ] The first declaration can be nested in `.comments` with the same output (no chance on specifity problems)
- [ ] Why style `ol` and `ul`, when `ol` is used?

#### _gallery.scss
- [ ] Can't this code be more compact or at least more DRY / calculated?

#### _logo.scss
- [ ] Rename `.sitename` and `.sitedescription` to `.site-name` and `.site-description` for readability

#### _navigation-icon.scss
- [ ] Rename this file to `_burger.scss` or rename `.burger` to `.navigation-icon`. I'd recommend the latter (maybe even `.mobile-navigation-icon`, to keep things description and consistent)

#### _search-form.scss
- [ ] Why are all elements named `.search-form-...` except for `.glass`? Would it be possible to make things more consistent?

#### _search-icon.scss
- [ ]  Rename this file to `_glass.scss` or rename `.glass` to `.search-icon`. I'd recommend the latter (maybe even `.search-form-icon`, to keep things descriptive and consistent)

#### _wordpress-images.scss
- [ ] I'm not sure this file is descriptive. `.alignleft` can be used for more things than images, right? Maybe this file should be split or something.
- [ ] If this file keeps to exist, it should be called `_wp-images.scss`, since we also have `_wp-caption.scss`.

#### Everything in `pages/`
- [ ] Remove it

## Conclusion
I'll start working on this as well. Maybe you guys can add to this list and keep it updated, so we have some kind of overview on the status. Big items or features can be placed as new issues.

I'd love to hear your thoughts.

**Comment by haroldangenent** [comment]
We talked about this. Notes:

> Separate structure and skin

We should do this.

> Inclusion order

Alphabetically, except when it's impossible.

> Mixins / functions

Will get their own directory. One mixin or function per file.

> Button mixin

Split in several mixins. Mixins used once will be declared in the appropriate class.

> Meta mixin

Will be removed.

> Block mixin (proposal)

We should try this.

> Block mixin (old one)

Rename it to something semantic.

> Gradient

Move to Fezcat.

> Parenthesis 

Every mixins should have parenthesis.

> Placeholder

Remove as proposed.

> List-style-none

Yes.

> Sprite mixin

Remove as proposed.

> Helpers

Remove.

> Typography

In a separate directory:

- `_base.scss` (also includes paragraphs)
- `_headings.scss`
- `_italic.scss` _maybe remove this_
- `_lists.scss`
- `_quotes.scss`
- `_code.scss`

> Footer

Keep the class.

> Header

Keep the class.

> Hentry

Different class and file name.

> Small a

Keep it.

> p.last-of-type

Remove it.

> Comments ol, ul

Put in parent. Remove `ul`.

> Gallery

Improve. Should be a separate issue.

> `.burger`

Rename to `.mobile-navigation-icon`.

> `.glass`

Rename to `.search-form-icon` or something. Also rename the file.

`_wordpress-images.scss`

Split if `.alignleft` is used for more than just images.

**New idea: create a `wordpress/` folder for all WordPress components.**

> pages/

Remove.

**Comment by haroldangenent** [comment]
>  The current block() mixin is too non-description. I'm not sure what it does and it doesn't even display: block

Based on some other frameworks and readings, I'd name it `.panel`, `.card` or `.box`. Maybe `.box` is the best one, since it's the most descriptive. The content is literally boxed in. I'll use that one, feel free to protest if you disagree.

**Comment by haroldangenent** [comment]
Just refactored `wordpress/` components. They include:

- `.wp-caption`
- `.comment-respond`
- `.comments`
- `.gallery`
- `_images.scss` (containing WYSIWYG image classes)

WordPress components can be defined as such: _Components which HTML is generated by either WordPress itself or it's WYSIWYG editor._

**Comment by haroldangenent** [comment]
I have decided to drop #543 out of this issue and rename this one. The modular approach is practically finished and can be improved upon in time. Separation of skin and structure is a separate issue completely.

**Comment by luukdv** [comment]
Agreed, as discussed. Excited about the merge.

**Comment by haroldangenent** [comment]
@gewoonderrik has tested it. Removed assignment.
