### ISSUE TITLE
Composer install script for namespaces

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#486]
We could create a composer install script (upon `create-project`) which replaces namespaces, `style.css` and maybe some more project-specific settings.

This request was a `wontfix` before, but since project-specific adjustments _have_ to be made when using PSR, this would be a better solution.

**Comment by haroldangenent** [comment]
Ready for testing (see PR #560).

**Comment by gewoonderrik** [comment]
Works!
