### ISSUE TITLE
Gulp: error notifier

### ISSUE THREAD

**Issue by sboerrigter** [trendwerk/trendpress#492]
Like a sound or native mac notification or something.

**Comment by haroldangenent** [comment]
`gutil.beep()` has been deprecated, we should use https://github.com/feross/beepbeep/.

**Comment by gewoonderrik** [comment]
Does it work on all types of errors? Seems to work most of the time. But for instance, when I change a variable name to something that doesn't exist, there's no bleep.

**Comment by gewoonderrik** [comment]
Never mind! Works just fine after restarting Gulp
