### ISSUE TITLE
Scrutinizer: use of global functionality

### ISSUE THREAD

**Issue by luukdv** [trendwerk/trendpress#493]
Line 15 in `template-tags.php`: Use of global functionality is not recommended; it makes your code harder to test, and less reusable.

**Comment by luukdv** [comment]
Don't know if there's an alternative.

**Comment by haroldangenent** [comment]
Scrutinizer is right. However, this is something that WordPress core uses. Therefore, we have to. I'll mark this as wontfix, feel free to reopen if you have any ideas.
