### ISSUE TITLE
Sass: use mix instead of darken and lighten

### ISSUE THREAD

**Issue by sboerrigter** [trendwerk/trendpress#498]
See http://sass-guidelin.es/#lightening-and-darkening-colors

**Comment by gewoonderrik** [comment]
Sounds like a good plan to me. I would like to add / applies the mixins if that's ok with you guys (cc @luukdv)

**Comment by sboerrigter** [comment]
Do you mean the function like provided in the example?

**Comment by gewoonderrik** [comment]
Yes. That's what I mean.

**Comment by sboerrigter** [comment]
Ok, let's do it.

**Comment by gewoonderrik** [comment]
Added and applied new color functions. Can someone please review?

**Comment by luukdv** [comment]
It seems like you added the mixin two times: https://github.com/trendwerk/trendpress/blob/master/assets/styles/_mixins.scss#L35

**Comment by gewoonderrik** [comment]
Removed double mixin. Can you have another look?
