### ISSUE TITLE
Sass: use HSL color notation

### ISSUE THREAD

**Issue by sboerrigter** [trendwerk/trendpress#499]
See http://sass-guidelin.es/#color-formats

**Comment by gewoonderrik** [comment]
HSL and keyword have been added. Can someone this?

This got me thinking about colour management and Sass. I think we should first define the colours by name in `_variables.scss` and then apply them. This seems like a more logical approach to me. It's also more maintainable. 

Example: 

```
$primary-color:        hsl(0, 0%, 20%);
$secondary-color:   hsl(0, 0%, 60%);
```

Should be: 

```
$medium-gray:    hsl(0, 0%, 60%);
$dark-gray:          hsl(0, 0%, 20%);

$primary-color:        $dark-gray;
$secondary-color:   $medium-gray;
```

What do you guys think?

**Comment by sboerrigter** [comment]
I agree. This is also what the Sass guidlines recommends.

**Comment by luukdv** [comment]
Yep, this is exactly as defined in the guidelines.

**Comment by luukdv** [comment]
Looks good. Do you think `$white: white;` is still necessary?

**Comment by gewoonderrik** [comment]
@luukdv No, not really. We should just use `white` instead.

**Comment by luukdv** [comment]
@gewoonderrik https://github.com/trendwerk/trendpress/issues/507
