### ISSUE TITLE
Use SassDoc for API

### ISSUE THREAD

**Issue by sboerrigter** [trendwerk/trendpress#500]
See http://sass-guidelin.es/#documentation

**Comment by sboerrigter** [comment]
w00t issue #500!

**Comment by gewoonderrik** [comment]
I sort of agree. Most mixins/extends are easy to understand. I would like to apply this to only to advanced mixins/extends (maybe `@mixin gradient` or `@mixin placeholder`).

**Comment by luukdv** [comment]
Agree with @gewoonderrik, but it seems like this is sort of a must in the guidelines.. Should we deviate from this?

**Comment by gewoonderrik** [comment]
@luukdv I don't know. I guess there's nothing wrong with commenting. And you're right... it does seem a bit like a standard.

**Comment by haroldangenent** [comment]
I think we should use [SassDoc](http://sassdoc.com/) for our API. Not only for the TrendPress API, but also for API's in our projects. Therefore, this issue should be twofold:

- Implement the SassDoc tool in [Gulp](https://www.npmjs.com/package/gulp-sassdoc)
- Actually write the documentation

**Comment by haroldangenent** [comment]
There is no support for Maps in SassDoc: https://github.com/SassDoc/sassdoc/issues/386. We nearly always use this.

I suggest we close this until there is support.

**Comment by luukdv** [comment]
Agreed.

**Comment by luukdv** [comment]
Closing this.
