### ISSUE TITLE
Sass: Use a Shame file

### ISSUE THREAD

**Issue by sboerrigter** [trendwerk/trendpress#501]
See: http://sass-guidelin.es/#shame-file

And maybe we should move everything we have now to that file and then move it to appropriate files from there once we have decided on #473.

**Comment by luukdv** [comment]
A shame file is used for important quickfixes, which have to be refactored later on. It's not a good idea to have such a thing in the theme by default. The styling should be good in the first place, without quickfixes.

**Comment by gewoonderrik** [comment]
I agree with @luukdv on this.

**Comment by sboerrigter** [comment]
Okay agreed.
