### ISSUE TITLE
Mention coding standards in comments, readme and/or wiki

### ISSUE THREAD

**Issue by sboerrigter** [trendwerk/trendpress#503]
Maybe we should mention the coding standards we use in the comments, readme file and wiki on github and link to the documentation about the coding standards.

**Comment by gewoonderrik** [comment]
@sboerrigter Can't see why not. :+1:

**Comment by luukdv** [comment]
:+1:

**Comment by haroldangenent** [comment]
Wiki seems like the proper place.

**Comment by sboerrigter** [comment]
I have added this to the Wiki: https://github.com/trendwerk/trendpress/wiki/Coding-standards

Please review.

**Comment by haroldangenent** [comment]
Revised some typo's.
