### ISSUE TITLE
Better colour management

### ISSUE THREAD

**Issue by gewoonderrik** [trendwerk/trendpress#504]
See #499. We should improve the color variables used in `_variables.scss`.

**Comment by luukdv** [comment]
I think we should create 1 issue regarding implementation of the guidelines instead of multiple small things

**Comment by gewoonderrik** [comment]
This isn't necessarily guideline related. It's more of an observation.

**Comment by haroldangenent** [comment]
I suspect you mean the names of the colors? If so, I agree.

**Comment by gewoonderrik** [comment]
The implementation of colours has been improved massively since last update. I'm closing this issue since it is no longer valid
