### ISSUE TITLE
Show mobile menu up until 980 breakpoint

### ISSUE THREAD

**Issue by luukdv** [trendwerk/trendpress#506]
Right now, this is the medium breakpoint. A lot of tablets and even a portrait iPhone 6+ are wider. Shall we change this to the 980 breakpoint?

**Comment by gewoonderrik** [comment]
Yes! I strongly agree with this. This is something I almost always change when I start working on a project.

**Comment by sboerrigter** [comment]
Fine with me.

**Comment by gewoonderrik** [comment]
Done. Can someone please review?

**Comment by luukdv** [comment]
Reviewed. Menu is broken, but that's a separate issue (#510).
