### ISSUE TITLE
Remove hr

### ISSUE THREAD

**Issue by gewoonderrik** [trendwerk/trendpress#508]
We should consider removing `hr` styles from `_typography.scss`. Personally, I haven used a `<hr>` element in ages.

Would like to hear everyones opinion on this.

**Comment by luukdv** [comment]
Yes. We could add all these 'special' typographic styles in a Gist if needed.

**Comment by gewoonderrik** [comment]
Removed this. Can someone please review?

**Comment by haroldangenent** [comment]
This has been removed in a fantastic manner. I will not close this issue, but will make it auto-close itself when the PR OOCSS has been merged.

**Comment by gewoonderrik** [comment]
Ok buddy ;)
