### ISSUE TITLE
Simplification: Remove ins and del 

### ISSUE THREAD

**Issue by gewoonderrik** [trendwerk/trendpress#509]
We should remove `ins` and `del` style from `_typography.scss`. We never use these styles and they're also not supported by the WordPress WYSIWYG editor (just like #508). 

Would like to hear everyones opinion!

**Comment by luukdv** [comment]
See https://github.com/trendwerk/trendpress/issues/508#issuecomment-127279191

**Comment by haroldangenent** [comment]
Actually, `ins` and `del` are part of WordPress editor's quicktags. See screenshot. They should at least look like they're supposed to. I'm not sure if we need code for that.

![schermafbeelding 2015-08-04 om 22 18 35](https://cloud.githubusercontent.com/assets/1481468/9071677/e107cc78-3af6-11e5-8b59-9a1a3cf34730.png)

**Comment by gewoonderrik** [comment]
If the WordPress editor supports these tags we shouldn't remove them. I've had another look at the styles. `<del>` has a strike-through now and lighter colour. `<ins>` has a darker colour and an underline. Does everyone agree with this?

**Comment by haroldangenent** [comment]
I noticed that my browser already does something like that. We can just remove it and let the browser figure it out, it's not worth the extra code imo.

@gewoonderrik what do you think?

**Comment by gewoonderrik** [comment]
@haroldangenent I agree. Want me to remove them?

**Comment by haroldangenent** [comment]
Removed them. Will be auto-closed when merged.
