### ISSUE TITLE
Main menu broken

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#510]
After [this commit](https://github.com/trendwerk/trendpress/commit/039986c72154464064c185da021048e7649659b4), the menu broke.

![schermafbeelding 2015-08-04 om 21 17 38](https://cloud.githubusercontent.com/assets/1481468/9070177/45e4dde2-3aee-11e5-88ea-9689431b5134.png)

**Comment by gewoonderrik** [comment]
Forgot to add `.sub-menu`. Should work now. Can someone have a look?

**Comment by luukdv** [comment]
Works again
