### ISSUE TITLE
Responsive typography

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#513]
This might be good. http://www.smashingmagazine.com/2015/06/responsive-typography-with-sass-maps/

**Comment by luukdv** [comment]
Agreed!

**Comment by gewoonderrik** [comment]
Added a responsive typography mixin with maps. Can someone please review?

**Comment by haroldangenent** [comment]
Some remarks on the code:

- Wouldn't it be possible to create one map for all font sizes? For example: 
```
$heading-sizes: (
  'h1': ...
);
```
- The keys are not encapsulated, but this is obliged according to [sass-guidelin.es](http://sass-guidelin.es);
- The `null` key feels weird;
- Do we really need maps for all headings? How about just h1 and h2?

**Comment by gewoonderrik** [comment]
* The keys are not encapsulated, but this is obliged according to sass-guidelin.es; - What do you mean by this?
* The `null` key feels weird; - Agreed. Let's change it to base or default.
* Do we really need maps for all headings? How about just h1 and h2? - Also agreed. What do you think @luukdv @sboerrigter?

**Comment by haroldangenent** [comment]
- That strings should be noted like `'this'` instead like `this`, so _with_ quotes.
- Okay, `default` is fine by me.

**Comment by gewoonderrik** [comment]
@haroldangenent Map vars are encapsulated now and I've renamed null to default

**Comment by haroldangenent** [comment]
@gewoonderrik Could you respond to my first remark?

- Wouldn't it be possible to create one map for all font sizes? For example:
```
$heading-sizes: (
  'h1': ...
);
```
- Should the last variable in the map have a comma?
- The `default` thing doesn't work. In fact, it generates the following (which doesn't work):
```
@media screen and (min-width: default) {
  h1 {
    font-size: 28px; } }
```
- I see you've split the `_variables.scss` file. However, I would split it by content type, not by variable type. Wouldn't it be more logical to have a `_colors.scss` file (all colors) and a `_typography.scss` file (line-height, font sizes and fonts)?

**Comment by haroldangenent** [comment]
Worked on this one.

- Only `h1` and `h2` are responsive now. `h3` and smaller seems like an overkill by default;
- Used one map called `$heading-sizes` instead of multiple maps;
- Removed `default` in favor of just `small`. The first key is the default now (so `small` in this case), since the theme is mobile first;
- Reorganized the variable files as follow:
 - `utils/variables/_breakpoints.scss`
 - `utils/variables/_colors.scss`
 - `utils/variables/_typography.scss`

I'll make the PR auto-close this. If someone still has remarks, please let me know.
