### ISSUE TITLE
Wiki: Page about development tools

### ISSUE THREAD

**Issue by sboerrigter** [trendwerk/trendpress#514]
I think we should add some information about our development tools and preprocessors to our Wiki. I have already added it here: https://github.com/trendwerk/trendpress/wiki/Development-tools. What do you guys think?

**Comment by haroldangenent** [comment]
Fixed some typo's and removed Composer. Composer is not used by TrendPress, but a TrendPress project can be created using Composer. This is already documented in the Wiki.

The rest seems good, simple and concise!
