### ISSUE TITLE
Suggestion: Tags lowercase should be removed

### ISSUE THREAD

**Issue by gewoonderrik** [trendwerk/trendpress#519]
Reason: Clients (or users) should decide for them self if they want to use lowercase tags (or not)

**Comment by haroldangenent** [comment]
:+1:

**Comment by haroldangenent** [comment]
@gewoonderrik They are all uppercased right now. Could you fix that?

_P.S. Could you just reference issues in your commit messages instead of adding 'fixes'?_

**Comment by gewoonderrik** [comment]
Fixed it. Sorry about 'fixes'. I don't know why I did that... :(

**Comment by haroldangenent** [comment]
Thanks, this will be auto-closed as well!
