### ISSUE TITLE
Vertical and horizontal spacing vars

### ISSUE THREAD

**Issue by gewoonderrik** [trendwerk/trendpress#520]
We should consider changing `$line-height` to `$vertical-space` and add a `$horizontal-space` as wel. Should be quite useful for universal indentation.

**Comment by luukdv** [comment]
Maybe in the same style as the breakpoint map, for optimal consistency.

**Comment by gewoonderrik** [comment]
@luukdv Yes.

**Comment by haroldangenent** [comment]
Maybe something like this: https://github.com/inuitcss/tools.mixins/blob/master/_tools.mixins.scss.

I think `$line-height` should continue to exist (as a map) for fonts. `$vertical-spacing` would define the default margin between two components.

**Comment by gewoonderrik** [comment]
Keeping it simple for now. Please review!
