### ISSUE TITLE
Allow ID's in linter

### ISSUE THREAD

**Issue by luukdv** [trendwerk/trendpress#522]
ID's are a perfectly valid feature. I think we should change `allow_element_with_id: false`, or we (and every plugin we need to style) can never use ID's again.

**Comment by haroldangenent** [comment]
I don't think we should use ID's as selectors. They're hardly ever necessary. When they are, we will be well aware and could try to find another solution first.

In TrendPress, ID selectors are not necessary anywhere (I've just removed them).

**Comment by gewoonderrik** [comment]
I agree with @luukdv on this one. More on this here: http://csswizardry.com/2011/09/when-using-ids-can-be-a-pain-in-the-class/

**Comment by haroldangenent** [comment]
Reading the article, it seems like you _don't_ want ID's.

I'd say we should conform to the guidelines. If there's a specific case that absolutely _has_ to use an ID, we could always allow them for that project. By default, the "No ID's" rule seems to be a good one.
