### ISSUE TITLE
Use trivial names for colors

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#523]
We should use trivial names for colors. From `_variables.scss`:

```
$white: hsl(0, 0%, 100%);
$black: hsl(0, 0%, 0%);
```

This should be:

```
$white: white;
$black: black;
```

See http://sass-guidelin.es/#color-formats.

**Comment by gewoonderrik** [comment]
@haroldangenent You're right. I've improved this now. Can you have a look?

**Comment by haroldangenent** [comment]
Looking good. Will be auto-closed.
