### ISSUE TITLE
Use variables for reusable colors

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#524]
From `_variables.scss`:

```
$primary-color: hsl(0, 0%, 20%);
...
$heading-color: hsl(0, 0%, 20%);
```

Wouldn't it be better to use a name for this color?
```
@grey: hsl(0, 0%, 20%);
...
@primary-color: @grey;
...
@heading-color: @grey;
```

http://sass-guidelin.es/#colors-and-variables

**Comment by gewoonderrik** [comment]
@haroldangenent This has been improved now. Can you have a look at the variables file?

**Comment by haroldangenent** [comment]
Nice! Changed a minor thing. Will be auto-closed.
