### ISSUE TITLE
_forms.scss is probably a dependency

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#525]
This file is used (in TrendPress) for resetting forms to default behaviour. This contents of this file are not meant to be modified.

Form resets, just like normal resets, could be the same for each website we create. Just like Normalize, there's a library called Formalize. We didn't like this a while ago. Some solutions:

- Review and maybe use Formalize;
- Find another form reset style that's good;
- Create our own as a package that can be used by several websites (in the form of a Bower package, perhaps).

I'd love to hear opinions on this.

**Comment by gewoonderrik** [comment]
Reasons why we shouldn't use Formalize:

* It's bigger than forms.scss (which seems logical of course)
* It adds button gradients and other styling we don't really need. Check out this [demo](http://formalize.me/jquery_demo.html). There's a focus shadow and gradients on the buttons. We could overwrite styles, but that doesn't make any sense.

There's quite a few form resets but no real industry standard. So it seems like a good idea to make our own package out of this.

**Comment by luukdv** [comment]
That's an option, but maybe we can look for some good, simple existing package first (other than formalize).

**Comment by haroldangenent** [comment]
I agree with @luukdv.

**Comment by haroldangenent** [comment]
By the way, our current `_forms.scss` also contains site-specific styling. We should keep this code, but it should be separate from the form reset.

**Comment by luukdv** [comment]
We've decided to keep styling-specific things, move comment styling to comment-respond and search for a quality forms reset library.

**Comment by haroldangenent** [comment]
@luukdv Giving this some priority, has been open too long.

**Comment by luukdv** [comment]
I've looked hard, but can't find a quality forms reset. They all try to do too much, are too opinionated or do so little that it's not really of added value. Examples:

https://github.com/ConciseCSS/concise.css/blob/master/src/_forms.scss
https://github.com/milligram/milligram/blob/master/src/_Form.sass
https://github.com/nathansmith/formalize/blob/master/assets/css/_formalize.scss
https://github.com/twbs/bootstrap/blob/master/less/forms.less#L1-L89

I think we should just take a good look at `_forms.scss` and rewrite where necessary, do some solid cross-browser testing and be done with it. Shouldn't be too big of a thing, browsers are pretty easy to deal with these days. What do you guys think?

**Comment by haroldangenent** [comment]
Agreed.

**Comment by haroldangenent** [comment]
We could optionally create a dependency out of the form reset, so the theme is not cluttered with any resets.

**Comment by luukdv** [comment]
Did a lot of cross-browser and device testing, this should be it.

**Comment by haroldangenent** [comment]
This seems way simpler. Noticed one issue:

- `[type="submit"]` and `[type="button"]` do not seem to `inherit` the `line-height` of `body`. Maybe add `line-height: inherit`?

**Comment by luukdv** [comment]
https://github.com/trendwerk/trendpress/commit/b58192cf5818638588f866216872d56fe8808ac9
