### ISSUE TITLE
Remove @section and @subsection comments in Sass

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#526]
This seems needless now everything is organized. It's also not a standard. We should apply the commenting standards from [sass-guideline.es](http://sass-guidelin.es) in a minimal way.

**Comment by gewoonderrik** [comment]
Agreed. I've refactored some of the old comments a couple of weeks ago.

**Comment by gewoonderrik** [comment]
Most comments have been removed. There's no need for comments with just the file name on the first few lines of the file itself. @haroldangenent Going to implement SassDoc. The few comments that remain are nested within bigger files (like `_main-navigation.scss`) and contain specific information. Please review!

**Comment by haroldangenent** [comment]
I agree.
