### ISSUE TITLE
Implement Sass functions

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#527]
For some calculations, we could [use functions](http://thesassway.com/advanced/pure-sass-functions) to make things more DRY.

**Comment by haroldangenent** [comment]
Maybe math helpers. https://github.com/inuitcss/tools.functions/blob/master/_tools.functions.scss

**Comment by luukdv** [comment]
I agree, but it's pretty general. Should this be a TrendPress issue?

**Comment by haroldangenent** [comment]
You're right. Closed.
