### ISSUE TITLE
Select arrow background position

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#537]
Currently situation:
```
background-position: 95% center;
```
Could be:
```
background-position: right 10px center;
```

Browser support is pretty good.

**Comment by gewoonderrik** [comment]
Any idea what happens on browsers that don't support this? Do they just apply `background-position: right 10px;` or something similar?

**Comment by haroldangenent** [comment]
No, it would look bad. Support: http://caniuse.com/#search=background-position.

So that would mean IE8 and UC Browser for Android. Just tested those, TrendPress already has bigger problems on those browsers.

**Comment by gewoonderrik** [comment]
Did some random tests. Looks like it's working just fine.
