### ISSUE TITLE
Refrain from WordPress output functions

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#539]
We're calling some output functions in the theme. A list below:

- ~~Galleries~~
- ~~Image classes~~
- ~~Caption~~
- Comments
- Comment respond form
- ~~Pagination #450~~
- ~~Menu #456~~

The first three, we cannot fix. They are added in the WYSIWYG editor and part of the content. We have to support those. They're not too bad anyway.

The latter two, we should have control over their output. Currently the output is generated by WordPress. We should do this ourselves in Twig ([using Timber](https://github.com/Upstatement/timber-starter-theme/blob/master/templates/single.twig)).

**Comment by luukdv** [comment]
Yup. An added benefit will be the output quality, since we have to some styling to make the WP output work.

**Comment by haroldangenent** [comment]
The first three are not possible. We should look into replacing WordPress functions with real HTML for:

- Comments
- Comments respond form

**Comment by haroldangenent** [comment]
@luukdv This needs testing as well. I've kept this in a separate branch, because it has high impact. See PR.

I've made some decisions about changing comments as well. I've listen them below.

- Simpler view (see changes in images below)
- Removed `comment-reply` script / interaction (See #644, wasn't possible before)
- Removed margin on `.comments`, had too much / inconsistent margin anyway
- No comments pagination, didn't see any possibilities using Timber
- Title above comments is now "Comments"
- Didn't replace `comment_form` with actual form. This seemed very complex and has a lot of exceptions we have to support. Also see [source of Timber](https://github.com/timber/timber/blob/master/lib/Post.php#L521)
- Comment depth: We're supporting a max depth of 1 now. Replies are possible, but until a depth of 1. See [this issue](https://github.com/timber/timber/issues/954) and [this seems related](https://github.com/timber/timber/issues/632)

Also see #704 for a discussion about making this into a starter and removing comments from TrendPress.

**Old**
![old](https://cloud.githubusercontent.com/assets/1481468/17174793/3e7ba98e-5404-11e6-9e14-46385133fc37.png)

**New**
![new](https://cloud.githubusercontent.com/assets/1481468/17174792/3e7a95a8-5404-11e6-953f-584402c716dd.png)

**Comment by luukdv** [comment]
Some styling is not perfect yet, but I don't think that should be a show stopper for merging since it wasn't perfect in the first place. I've created an issue to improve the styling a bit.

![screen shot 2016-08-03 at 18 02 58](https://cloud.githubusercontent.com/assets/5585947/17372674/2aa29656-59a5-11e6-93bf-f9813481866e.png)
![screen shot 2016-08-03 at 18 06 42](https://cloud.githubusercontent.com/assets/5585947/17372673/2aa21848-59a5-11e6-8f98-58a6136e5cb7.png)
