### ISSUE TITLE
Separate structure from skin

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#543]
According to OOCSS, we should _"Separate structure from skin"_. However, this would mean we should create skins for all components. As you can see in the official repository of OOCSS, this is [not very consistent](https://github.com/stubbornella/oocss/tree/master/oocss/src/components) here as well.

Two questions we should answer:
- Do we want to separate structure from skin? And why?
- How could this approach be implemented?

**Comment by luukdv** [comment]
This is a difficult and important one. Maybe we should all think about it, read up on different options a bit and discuss it IRL.

**Comment by gewoonderrik** [comment]
We're closing this issue, because separating structure from skin wouldn't add anything. Skin is already modular, because we use variables.

The only reason to separate this is to be more modular and reusable. This should be discussed in #565.
