### ISSUE TITLE
Interaction on devices

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#544]
To make it feel more responsive, tags and buttons should respond immediately when tapping them.

**Comment by luukdv** [comment]
You mean activating the hover/active/focus state when you interact with the elements?

**Comment by haroldangenent** [comment]
Yes. Especially when clicking buttons or just a `box-link()`.

**Comment by luukdv** [comment]
I disagree. You can implement this by adding things like `ontouchstart=""` to the `body` tag and setting `tap-highlight-color` to `transparent`, but this feels weird when scrolling a page with your finger. Every time you enter the tapzone of these elements this state will activate, implying you accidentally clicked the button. Default mobile browser behaviours usually handle this a lot better - and it's more recognizable for users.

**Comment by haroldangenent** [comment]
It should only be activated when actually following the link. Same behaviour as on desktop.

**Comment by luukdv** [comment]
But the browser has no way of knowing if you're going to release and follow the link or continue to scroll. Let's talk about this in real life with some examples, maybe I'm missing something.

**Comment by luukdv** [comment]
I have been thinking a lot about this lately, and feel it's an important issue. We might want to have a look at integrating some of the new ng material design. For example, check out one of the buttons (https://material.angularjs.org/latest/demo/button) on mobile. They feel completely intuitive and responsive (immediate feedback on focus/tap/mouseDown etc).

**Comment by haroldangenent** [comment]
:+1:

**Comment by haroldangenent** [comment]
See patch for quick example. I'm not sure how to deal with buttons (or anything) created in WYSIWYG editors. Any ideas?

[md-ink-ripple.diff.zip](https://github.com/trendwerk/trendpress/files/148591/md-ink-ripple.diff.zip)

**Comment by luukdv** [comment]
Haven't tried it out yet but looks clean, maybe we shouldn't add classes at all and control everything from an Angular service itself. https://material.angularjs.org/1.0.0/api/service/$mdInkRipple seems to do the trick.

**Comment by luukdv** [comment]
As discussed: only `ontouchstart` for now.

**Comment by luukdv** [comment]
Doesn't seem to be working on Android, and still feels like a sort of hack. I'm having doubts right now if we should keep this.
