### ISSUE TITLE
Defer main JavaScript file by default

### ISSUE THREAD

**Issue by luukdv** [trendwerk/trendpress#547]
I feel this should be in our framework. Related to #546.

**Comment by haroldangenent** [comment]
Yes.

**Comment by gewoonderrik** [comment]
Works!

**Comment by gewoonderrik** [comment]
@haroldangenent Fancybox causes an error in the latest version of the theme. Not sure why.

**Comment by gewoonderrik** [comment]
@haroldangenent Must have done something wrong. It works now!
