### ISSUE TITLE
Image alignment unit test fail

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#558]
![schermafbeelding 2015-10-02 om 14 36 07](https://cloud.githubusercontent.com/assets/1481468/10246601/f5eef284-6912-11e5-8e70-0273e75e7a5b.png)

On the post `/markup-image-alignment/` from Automattic's unit tests.

**Comment by sboerrigter** [comment]
Nope...

![screen shot 2015-10-02 at 16 09 13](https://cloud.githubusercontent.com/assets/786875/10248463/f1436e38-691f-11e5-9d1c-20d27e89c9f6.png)

**Comment by gewoonderrik** [comment]
Please check again @sboerrigter

**Comment by sboerrigter** [comment]
Looks good now.
