### ISSUE TITLE
Lint config: DeclarationOrder

### ISSUE THREAD

**Issue by luukdv** [trendwerk/trendpress#571]
The lint config we use is not built for a mobile-first approach since it forces media queries to the top with `DeclarationOrder`. I believe this setting should be set to false by default.

**Comment by sboerrigter** [comment]
I agree

**Comment by haroldangenent** [comment]
I disagree. Bubbling means defining the media queries inside the specific element which it's meant for. I think we should do this in a consistent way.

**Comment by sboerrigter** [comment]
I don't think you get the point. This isn't about bubbling, but about putting the media query after the other css declarations. The Sass linter says we can't do this, but this is necessary if we work mobile-first.

**Comment by haroldangenent** [comment]
I've stumbled across this a number of times, where I thought the media query had to be later, but I was mistaken. I didn't bubble correctly.

Could you give me a use-case of when this is an issue when bubbling correctly?

**Comment by sboerrigter** [comment]
Can't think of an example right now, but I'll let you know when I have this problem in the wild.

**Comment by haroldangenent** [comment]
I'm closing this because this hasn't been a problem when using bubbling correctly. Feel free to reopen if I'm mistaken.
