### ISSUE TITLE
Removing CoffeeScript

### ISSUE THREAD

**Issue by luukdv** [trendwerk/trendpress#576]
I think we should remove CoffeeScript in favor of vanilla JS, for a variety of reasons. Can we discuss this the next time we work on the theme?

**Comment by luukdv** [comment]
This includes a JS linter and some JS coding standards.

**Comment by luukdv** [comment]
Everyone agrees as discussed IRL.

**Comment by luukdv** [comment]
Add JSLint

**Comment by haroldangenent** [comment]
Comments in `gulpfile.js` still say "Coffee".
