### ISSUE TITLE
Class 'Timber' not found

### ISSUE THREAD

**Issue by abr4xas** [trendwerk/trendpress#580]
Hi there,

`Fatal error: Class 'Timber' not found in /var/www/wordpress/wp-content/themes/trendpress/index.php on line 2`

**Comment by luukdv** [comment]
Hi abr4xas,

Can you check if you didn't forget to activate the 'Timber' plugin?

**Comment by haroldangenent** [comment]
Notices this was not in the Wiki. Add Timber: https://github.com/trendwerk/trendpress/wiki/Installation#timber.
