### ISSUE TITLE
Move main navigation to header

### ISSUE THREAD

**Issue by sboerrigter** [trendwerk/trendpress#583]
Hello. 

In almost every website we create the main navigation is in the header, next to the logo. I think we should make this menu position the default state in WordPress. We can replace the search box with a search toggle button to make more room for the menu.

**Comment by luukdv** [comment]
:+1:

**Comment by haroldangenent** [comment]
:+1:

**Comment by sboerrigter** [comment]
I also removed the search function from the theme and modified the 404 error page. Please test this as well.
