### ISSUE TITLE
Match font styles to default Sketch file

### ISSUE THREAD

**Issue by sboerrigter** [trendwerk/trendpress#588]
Like this:

![font-styles](https://cloud.githubusercontent.com/assets/786875/13147840/d4be6a44-d65a-11e5-998c-85d6d4072803.png)

I don't think we need the "Text small" and "Text extra small" by default.

**Comment by luukdv** [comment]
:+1:

**Comment by haroldangenent** [comment]
:+1:

**Comment by luukdv** [comment]
Looks good, some stuff is different (like meta font-weight, h1 size, margins), but I guess that's intentional?

**Comment by sboerrigter** [comment]
Yes, this is intentional. I changed meta in the sketch file as well.
