### ISSUE TITLE
Image alignment like in default Sketch file

### ISSUE THREAD

**Issue by sboerrigter** [trendwerk/trendpress#589]
Like this:

![image-alignment](https://cloud.githubusercontent.com/assets/786875/13147870/055fc378-d65b-11e5-96d1-f5b5378ff6a0.png)

**Comment by luukdv** [comment]
Agreed, already created this for another project. We might be able to use that.

**Comment by luukdv** [comment]
I think they break a bit early, could be solved by resizing the images on smaller screens. Thay way they can stay next to the content a little longer.

**Comment by luukdv** [comment]
These images don't have margins on smaller screens since the margins are defined in the large breakpoint:

![screen shot 2016-03-17 at 18 18 38](https://cloud.githubusercontent.com/assets/5585947/13854685/fe61807a-ec6c-11e5-9049-8f9218dcb517.png)

**Comment by sboerrigter** [comment]
Can you check again?

**Comment by luukdv** [comment]
I can't see any differences.
