### ISSUE TITLE
Alignment postmeta

### ISSUE THREAD

**Issue by sboerrigter** [trendwerk/trendpress#590]
Should be closer to the title:

![screen shot 2016-02-18 at 16 41 06](https://cloud.githubusercontent.com/assets/786875/13148644/818ca792-d65e-11e5-8f1b-a2ae5d2e59de.png)

**Comment by haroldangenent** [comment]
:-1: we removed this earlier for a consistent `h1` margin.

**Comment by sboerrigter** [comment]
Re-add margin on single post.

**Comment by haroldangenent** [comment]
- There was a weird CSS file in your commit
- `font-size` in meta is 18px right now. Aren't there any other places that need this font size? Tags, for example. Shouldn't we make a variable or use the one from `_typography.scss`?
- Changed the `_single.scss` margin to vertical spacing / 4, as discussed
- `.single` is too generic, could you use `.single-post`? `.single` would be applied to any post type

**Comment by sboerrigter** [comment]
* single.css: Weird. I don't have the file locally and it's not in the repo anymore.
* Font-size variable: done
* Vertical spacing: ok
* Rename `_single.scss`: done
