### ISSUE TITLE
Make TrendPress wider

### ISSUE THREAD

**Issue by sboerrigter** [trendwerk/trendpress#591]
1200px wide on dekstop like the default Sketch file.

**Comment by luukdv** [comment]
Yes.

**Comment by sboerrigter** [comment]
LOL

Anyway. We should also remove the 980px grid system. I think the site should be fluid until a maximum width of 1200px.

**Comment by luukdv** [comment]
Agreed, like pointed out before.

**Comment by sboerrigter** [comment]
Remove 'huge', replace 'large' with it's value. Make it good.

**Comment by sboerrigter** [comment]
At 981px the main contents gets a little wider. I think we should change the media query "large" to 921px, so it looks smooth when you resize the screen.

**Comment by luukdv** [comment]
I don't agree, we should define the content-width in another way.

**Comment by sboerrigter** [comment]
I agree, but can we change only this media query to 921px until we fixed #612?

**Comment by sboerrigter** [comment]
Why did you close this?

**Comment by haroldangenent** [comment]
I think we should close this in favor of #612.

**Comment by luukdv** [comment]
Agreed.
