### ISSUE TITLE
word-wrap

### ISSUE THREAD

**Issue by luukdv** [trendwerk/trendpress#598]
As discussed: let's set `break-word` site-wide. Maybe conduct a quick research for possible disadvantages before changing.

**Comment by sboerrigter** [comment]
:+1: Take a look at `hyphens`.

**Comment by gewoonderrik** [comment]
Apparently `hyphens: auto` has a very small support range. Check out this [support table](https://developer.mozilla.org/en/docs/Web/CSS/hyphens) for more info on the matter. Not sure if we should add this by default. Thoughts?

**Comment by luukdv** [comment]
Should be `word-wrap` (`break-word` doesn't exist for `word-break`).
