### ISSUE TITLE
Link hover is the same color as link

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#602]
On titles of archive pages it's exactly the same. On normal links it's almost the same. Maybe hover to another color (like blue)?

**Comment by sboerrigter** [comment]
I changed this in the last release (while working on the typography styles). What do you think about this now? I'd like to keep the links in greyscale, because everything is in grey scale by default.

**Comment by haroldangenent** [comment]
The archive pages hover color is the same as the non-hover color. It's not really clear that this is a link right now. I don't think we should make exceptions for each element, but choose a link color that's always clear.

**Comment by sboerrigter** [comment]
I have added a `$hover-color` variable and used it to define the hover colors.

**Comment by luukdv** [comment]
Looks good.
