### ISSUE TITLE
Distances between elements

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#605]
I believe every element should be either responsible for the distance below itself or the distance above itself. Right now, things often are a mess.

To streamline this, we could have a mixin to give an element it's distance. This should be standardized in a variable, so that it can only be consistent. 

Distances should be smaller on smaller screens.

**Comment by sboerrigter** [comment]
I agree. We allready have the $vertical-spacing; and $horizontal-spacing; variable. Maybe we could use those?

**Comment by haroldangenent** [comment]
Maybe. But these variables seem abused some times. For example:

```
$vertical-spacing * 1.5
$vertical-spacing / 8
$vertical-spacing / 4
```

This doesn't seem like they're actually related, but like manipulating a variable so it comes out the way you want. I'm not sure that if we change `$vertical-spacing` right now, everything is as it's supposed to be.

**Comment by sboerrigter** [comment]
I agree. How do you suggest to do this?

**Comment by haroldangenent** [comment]
I imagine something like this:

```
$distances: (
  'small': 20px,
  'medium': 40px
);
```

And a mixin for actually creating the distances:

```
@mixin element-distance() {
	@each $breakpoint, $distance in $distances {
		// Distance the element to the next or previous one, using either margin top or bottom.
	}
}
```

Each instant where `$vertical-align` is used right now should be properly investigated and thought about.

**Comment by haroldangenent** [comment]
We decided on `margin-bottom` and `margin-right` to give elements it's distance in relation to other elements. The entire theme needs to be reviewed and we have to provide a consistent solution for distances between elements.

**Comment by haroldangenent** [comment]
@luukdv Maybe, instead of `element-distance()` as mentioned above, we could re-use `responsive-margin-bottom()`, which automatically calculates smaller screens based on `$breakpoints`.

We could set a `$margin-bottom-default` in `_dimensions.scss`.

**Comment by haroldangenent** [comment]
I suggest introducing a `responsive-property()` mixin and a `responsive-margin-bottom()` mixin. `margin-bottom` will get it's own mixin for easyness and to set a default when no parameter is given.

**Comment by haroldangenent** [comment]
See #719 for an exhaustive list of elements that should be targeted.

**Comment by haroldangenent** [comment]
Forgot to tag https://github.com/trendwerk/trendpress/commit/ee77937c3c1642db5af4f15c0a5f6a0e4ff4d9b8.

**Comment by luukdv** [comment]
Looks good! (including https://github.com/trendwerk/trendpress/commit/c4ad65e0e1b37e818d8314f2810f9049e8d6bc74)
