### ISSUE TITLE
Improve button styles

### ISSUE THREAD

**Issue by sboerrigter** [trendwerk/trendpress#608]
I think the buttons look ugly with the new text styles. Shall we make them look more like this?

![screen shot 2016-03-17 at 15 09 28](https://cloud.githubusercontent.com/assets/786875/13851851/06b1ca3a-ec60-11e5-9591-5d58f95896a1.png)

**Comment by luukdv** [comment]
And other button-like stuff, tags and pagination for example.

**Comment by haroldangenent** [comment]
I don't think we should re-introduce a `border-radius` variable or small buttons. I agree on the rest.

**Comment by sboerrigter** [comment]
I've just improved this in https://github.com/trendwerk/trendpress/commit/18ec72f7c7bb2f752688dacea3caf8deffcea62f.

The button height is not working correctly. But I think this is a problem with `box-link`. See: #622 .

I also think the button looks better with bold text instead of semibold text (like in the screenshot above). But if we change this, we have to load an extra font style. Do you guys think this is worth it?

**Comment by haroldangenent** [comment]
I agree, but I don't think it's worth it. Tested the commit. Close it if you'd like.
