### ISSUE TITLE
Image style isn't displayed correctly in the WordPress editor

### ISSUE THREAD

**Issue by sboerrigter** [trendwerk/trendpress#609]
![screen shot 2016-03-17 at 16 41 58](https://cloud.githubusercontent.com/assets/786875/13851877/1e957aca-ec60-11e5-9f75-caea22d2a7ce.png)

**Comment by haroldangenent** [comment]
Also for `.alignnone` images.

**Comment by haroldangenent** [comment]
Margin seems off.

![schermafbeelding 2016-05-09 om 15 30 21](https://cloud.githubusercontent.com/assets/1481468/15114634/220512be-15fb-11e6-8d71-63f1666d1d80.png)

**Comment by sboerrigter** [comment]
I can't reproduce this issue (see screenshots). Can you please show me IRL?

![screen shot 2016-05-12 at 13 56 33](https://cloud.githubusercontent.com/assets/786875/15213765/75445688-1849-11e6-8fa9-d127f26592b4.png)

![screen shot 2016-05-12 at 13 56 46](https://cloud.githubusercontent.com/assets/786875/15213766/75572510-1849-11e6-95a7-d82a77ffaa97.png)

**Comment by sboerrigter** [comment]
Appearantly WordPress adds `float` attribute to left and right aligned images in the back-end. I overruled this.

**Comment by haroldangenent** [comment]
When breaking out the images on larger screens, it breaks the editor.

**Comment by haroldangenent** [comment]
Also, `float: none` should be removed on images in the front-end.
