### ISSUE TITLE
Improve pagination

### ISSUE THREAD

**Issue by sboerrigter** [trendwerk/trendpress#614]
Pagination doesn't look right with the new typography styles.

![screen shot 2016-03-17 at 17 46 40](https://cloud.githubusercontent.com/assets/786875/13854486/06659cb2-ec6c-11e5-9b6f-142f438815eb.png)

**Comment by luukdv** [comment]
See https://github.com/trendwerk/trendpress/issues/608

**Comment by sboerrigter** [comment]
Improved this in https://github.com/trendwerk/trendpress/commit/f53cca19e869bfd52dc94d3c67256b99ad6f2d32. Needs testing.

<img width="844" alt="screen shot 2016-03-17 at 23 07 53" src="https://cloud.githubusercontent.com/assets/786875/13862724/49b32740-ec95-11e5-8ca6-7c923ca91f97.png">
