### ISSUE TITLE
Alignnone image styling

### ISSUE THREAD

**Issue by luukdv** [trendwerk/trendpress#616]
Should be the same as `aligncenter` images.

**Comment by sboerrigter** [comment]
I disagree. Why would you center align an image if it is'nt supposed to?

**Comment by haroldangenent** [comment]
IMO, `.alignnone` means 'align like default'. The default alignment should be set in the theme. To me, the question is: 'What alignment do we want in the theme by default?'.

Therefore, I agree with @luukdv. Aligning images in the center is the most beautiful by default.
