### ISSUE TITLE
Wrapper padding as a variable

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#617]
So it can be used for calculations.

**Comment by sboerrigter** [comment]
@haroldangenent can you please explain what you mean with this issue?

**Comment by haroldangenent** [comment]
Create a variable or map for [wrapper padding](https://github.com/trendwerk/trendpress/blob/master/assets/styles/layout/_wrapper.scss#L2), instead of using the horizontal padding (that is always overwritten by a specific amount), so the wrapper padding can be used in calculations throughout a website.
