### ISSUE TITLE
Refactor _images.scss

### ISSUE THREAD

**Issue by sboerrigter** [trendwerk/trendpress#620]
I though _images.scss could be better, so I improved it. See: https://github.com/trendwerk/trendpress/commit/1214694767b18a46c1db37400624c7ea11781eac

Whay do you guys think?

**Comment by haroldangenent** [comment]
I think you could also remove `height: auto` and `max-width: 100%`, because all images have those declarations already.

**Comment by sboerrigter** [comment]
Agreed. I removed it.
