### ISSUE TITLE
Remove utils/mixins/_caption.scss

### ISSUE THREAD

**Issue by sboerrigter** [trendwerk/trendpress#621]
I think we should remove this mixin. It is only used in two places, but it doesn't look right in _gallery.scss.

**Comment by haroldangenent** [comment]
I'm not sure what you mean. Do you want to remove support for captions in images or galleries? Or both?

Right now, the gallery inherits the caption aspects and does some things to make it suitable for a gallery caption. I agree that it doesn't like good right now.

**Comment by sboerrigter** [comment]
I don't want to drop caption support. I suggest to move styling for captions from `/utils/mixins/_caption.scss` to `/components/wordpress/_caption.scss`, and make new caption styling for `_gallery.scss` when we work on #532.

**Comment by haroldangenent** [comment]
If it still shares code because they look alike, I think we should keep `caption()`. If they will be completely separate, we should separate the code. I agree we should take a look when working on #532.

**Comment by sboerrigter** [comment]
Okay. I'll close this.
