### ISSUE TITLE
Posts with comments disabled have an empty div.

### ISSUE THREAD

**Issue by sboerrigter** [trendwerk/trendpress#623]
<img width="1080" alt="screen shot 2016-03-17 at 22 45 24" src="https://cloud.githubusercontent.com/assets/786875/13862248/518a4794-ec92-11e5-914b-6345a0c5f797.png">

**Comment by sboerrigter** [comment]
Related to: #539

**Comment by haroldangenent** [comment]
Is this ready for testing?

**Comment by sboerrigter** [comment]
yes
