### ISSUE TITLE
Variable for wrapper width

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#624]
https://github.com/trendwerk/trendpress/commit/36a233d24294a7a1924a426664a1bbe29b227b66 These seem related. If you change one, the other should change as well.

**Comment by sboerrigter** [comment]
@haroldangenent can you please explain what you mean with this issue?

**Comment by haroldangenent** [comment]
The units from that commit seem related. If one changes, the other should be changed.

Introduce a variable, so this is more consistent.

**Comment by haroldangenent** [comment]
Did a few other small optimizations, see commits.
