### ISSUE TITLE
Maybe use `spaceless`

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#626]
http://twig.sensiolabs.org/doc/tags/spaceless.html

Boxed links (pagination or tags) have some extra margin now, because of spaces. Twig can strip these for us.

**Comment by luukdv** [comment]
Nice. Seems like the strip operators (`-`) before and after twig variables (`page.title` in `pagination.twig` and `term.name` in `tags.twig`) can be removed now?

**Comment by haroldangenent** [comment]
Nice catch.
