### ISSUE TITLE
Caption padding

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#628]
It should have some.

![schermafbeelding 2016-03-18 om 11 30 11](https://cloud.githubusercontent.com/assets/1481468/13875202/d04fdd36-ecfc-11e5-9e77-4bce57cd140c.png)

**Comment by haroldangenent** [comment]
Has padding now, but a slightly longer caption breaks out of it's parent.

![schermafbeelding 2016-05-09 om 15 24 34](https://cloud.githubusercontent.com/assets/1481468/15114415/2fcf57e8-15fa-11e6-8d2d-07eb6fbf4e6f.png)
![schermafbeelding 2016-05-09 om 15 23 47](https://cloud.githubusercontent.com/assets/1481468/15114416/2fd03370-15fa-11e6-8098-3e37f1e3cc0f.png)

**Comment by luukdv** [comment]
Also, it's pretty big (font-size and line-height) and there's a weird looking shadow.
