### ISSUE TITLE
Button mixinception

### ISSUE THREAD

**Issue by sboerrigter** [trendwerk/trendpress#634]
I think the mixin structure of buttons is a bit confusing. 

- `components/button` uses the mixin `utils/mixins/button`
- `utils/mixins/button` uses the mixin `utils/mixins/box-link`
- `utils/mixins/button` uses the mixin `utils/mixins/box`

I think this can be simplified. Maybe we should have a maximum 'mixin depth' of 2?

**Comment by haroldangenent** [comment]
I do not agree. This just is inheritance. You would have to think about which value to manipulate a bit more, yes, but it's way more DRY and logic.

`box` can be used for any type of boxed content (for example, a sticky post)
`box-link` is a type of `box` that is also a link (for example, a tag, button or pagination.)
`button` is a specific type of `box-link`

This allows us to actually see the logic behind elements, their behaviour and their styling. If anything, I think we should write _more_ code like this.

By declaring this as mixins it's not only more DRY and consistent, it also provides a way to describe the general structure of a website and it's elements.
