### ISSUE TITLE
Inclusion order main.scss

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#638]
As the title says. Seems more logic than above `components/`.

**Comment by sboerrigter** [comment]
Maybe we should use the order in http://sass-guidelin.es/#architecture (see: main file).

**Comment by sboerrigter** [comment]
Related to: #555

**Comment by haroldangenent** [comment]
I see. Specific changes:

- `utils` is now called `abstracts`
- `vendors` is below `abstracts` (for us these are Bower components)
- `pages` below `components`

**Comment by sboerrigter** [comment]
I've changed the Sass include order.

We cannot put the bower components (or `vendor`) below the other includes, because the `toggle-navigation` mixin wouldn't work anymore.

**Comment by haroldangenent** [comment]
> We cannot put the bower components (or vendor) below the other includes, because the toggle-navigation mixin wouldn't work anymore.

Why not? `abstracts/` just contain definitions (symbols), no mixin calls (side-effects). Just tested this, seems to work.

**Comment by haroldangenent** [comment]
And `layout/` should be before `components/`.
