### ISSUE TITLE
Remove text-decoration from _links.scss

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#642]
From `_links.scss`:

```
  text-decoration: underline;

  &:hover {
    text-decoration: underline;
  }
```
Nothing happens when I remove both.

**Comment by haroldangenent** [comment]
See https://github.com/trendwerk/trendpress/commit/b03eb049e2dc718d865cb6e8374af14ef1421ee4.

**Comment by luukdv** [comment]
I don't really like that we're now trusting all browsers to add this by default in their own styles, I'm more for the explicit declarations (like before). But if it works cross-browser, it's fine. :)
