### ISSUE TITLE
Markup: Image alignment, wide image is overflowing

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#643]
When using Automattic's test data: /2013/01/10/markup-image-alignment/

![schermafbeelding 2016-04-15 om 16 14 53](https://cloud.githubusercontent.com/assets/1481468/14564074/392362ae-0325-11e6-97ec-3df11e6ab997.png)

I'm not sure if this should actually be fixed.

**Comment by luukdv** [comment]
I think it should. I'm curious as to why this happened since we've always had 'max-width: 100%' on images, maybe it was accidentally deleted sometime?

**Comment by sboerrigter** [comment]
I think this issue has allready been fixed.
