### ISSUE TITLE
Disable inline comments with JS

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#644]
We could (by default) disable inline comments. You can still comment to someone, just not inline.

Added bonus: we can remove `wp_enqueue_script('comment-reply');`, which is hardly used.

**Comment by luukdv** [comment]
Another added bonus: less styling needed (I think?)

**Comment by haroldangenent** [comment]
Will produce a JavaScript error which is not solvable. There's no way to delete this unless we delete comments altogether.
