### ISSUE TITLE
Remove specified type link/script

### ISSUE THREAD

**Issue by gewoonderrik** [trendwerk/trendpress#646]
We should remove `type="..."` from our JavaScript and CSS includes. Text/css and text/javascript are defaults so there's no need to include `type`.

See [codeguide.co](http://codeguide.co/) for more info

**Comment by haroldangenent** [comment]
Since these are only 2 includes and the code is handled by WordPress, I suggest to keep using this handled by WordPress for now.

**Comment by haroldangenent** [comment]
Closing this.
