### ISSUE TITLE
Check for unnecessary mark-up

### ISSUE THREAD

**Issue by gewoonderrik** [trendwerk/trendpress#648]
We should have a look at our files to see if there's any unnecessary mark-up and remove and/or improve it

See [codeguide.co](http://codeguide.co/) for more information

**Comment by haroldangenent** [comment]
@gewoonderrik What do you exactly mean by unnecessary mark-up? Seems really general. What exactly should be checked?

**Comment by haroldangenent** [comment]
Checked all files, see commit.
