### ISSUE TITLE
HTML: Use soft tabs (2 spaces)

### ISSUE THREAD

**Issue by gewoonderrik** [trendwerk/trendpress#650]
Like discussed in the presentation a few weeks ago we should: 

- Use soft tabs (2 spaces). This can be a default in our code editors
- ~~Group our code more logical (not just use a white line after each line of code)~~

We should have a look at our theme and make sure that our theme complies to these standards

**Comment by haroldangenent** [comment]
I'm creating a second issue for point 2.
