### ISSUE TITLE
Images with captions are to wide on smaller screens

### ISSUE THREAD

**Issue by sboerrigter** [trendwerk/trendpress#658]
![screen shot 2016-04-28 at 17 33 51](https://cloud.githubusercontent.com/assets/786875/14891551/6a7b35ba-0d67-11e6-9a5b-761e89f5ee77.png)

**Comment by haroldangenent** [comment]
@sboerrigter Could you clarify in which use-case this happens? Cannot reproduce this bug.

I can reproduce the wide image (#643), but it doesn't have anything to do with `.wp-caption`. Are you this this is the right approach?

**Comment by sboerrigter** [comment]
When did you test this? This issue has allready been fixed. If you remove line 2 of `components/wordpress/_caption.scss` you'll see the difference.

Images with a caption are wrapped in a span. That's why `img { max-width: 100%; }` doesn't work.

**Comment by haroldangenent** [comment]
Good.
