### ISSUE TITLE
'$line-height-small' variable

### ISSUE THREAD

**Issue by sboerrigter** [trendwerk/trendpress#661]
We have a variable `$line-height: 2;`, but we also use the line-height `1.5` very often in the theme (for headings, blockquotes and captions for example). 

Maybe we should make a secons variable for this value (eg. `$line-height-small: 1.5;`)?

**Comment by haroldangenent** [comment]
A `line-height` mixin would probably be best, so we don't have three separate variables:

```
$line-height-header
$line-height
$line-height-small
```

but

```
$line-height: (
  'base': ...,
  'header': ...,
  'small': ...,
);
```

I'd only create a variable for `1.5` if these instances are actually logically connected, which I'm not sure of. Headings now have a `line-height` of `1.325`.

**Comment by sboerrigter** [comment]
The heading line-height sould be 1.5 according to the styleguide.

**Comment by haroldangenent** [comment]
Heading `line-height` should also be in this map (it's a separate line-height now).

**Comment by haroldangenent** [comment]
Maybe something like this:

```
$line-height: (
  'heading': 1.5,
  'toggle-navigation': 2.5,
  'text': 2,
);
```

The `toggle-navigation` line-height would be the line-height for menu items when the toggle menu is open.

**Comment by luukdv** [comment]
Nice. In `_footer.scss` there's a line-height of `30px`, can't this be the base line-height?

**Comment by sboerrigter** [comment]
Updated it. Can you check again?
