### ISSUE TITLE
Consistent use of Sass filenames

### ISSUE THREAD

**Issue by sboerrigter** [trendwerk/trendpress#662]
Sometimes we use singluar names for Sass filenames (e.g. `button.scss`, `post.scss`, `gallery.scss`). And sometimes we use plural names (e.g. `links.scss`, `lists.scss`, `images.scss`).

I think we should make this more constant. I suggest we only use singular names, unless the element it targets also has a plural classname (like `tags.scss`).

**Comment by haroldangenent** [comment]
Seems fine. It would be a bit nicer if you'd commit the name change of `wordpress/_images.scss` separately to keep moving in as small steps as possible.
