### ISSUE TITLE
Use grid() for gallery

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#663]
So things are always beautiful. Right now, the images do not fill out the entire content width and on responsive they don't either. Grid fixes these issues.

The thumbnail size should be larger because of this.

**Comment by luukdv** [comment]
Completely agree. With grid, it looks much better. See some of our recent projects for reference.

**Comment by luukdv** [comment]
Removing the discussion label since nobody disagrees.

**Comment by luukdv** [comment]
Researching options on overwriting WP's output with custom timber output to make use of `grid()` and responsive images in a better way (https://github.com/trendwerk/trendpress/tree/gallery-grid).

**Comment by haroldangenent** [comment]
That's great. Do you estimate this would be possible for all other items from #539?
