### ISSUE TITLE
.logo should use $line-height-header

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#664]

**Comment by haroldangenent** [comment]
Maybe also for the `.menu-item a {}` line height.

**Comment by sboerrigter** [comment]
I also head to add `display: inline-block;` for it to have effect.

I've aso implemented this for `.menu-item a`, but I'm not sure if we should do this. What do you guys think?

**Comment by haroldangenent** [comment]
Made a semantic change, because horizontal and vertical padding should not be connected.
