### ISSUE TITLE
Use ESLint

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#670]
http://eslint.org/

Maybe use ESLint, since JSHint only limits itself to code correctness.

**Comment by haroldangenent** [comment]
Gulpfile still contains things about `CoffeeScript`. Can be removed when working on this.

**Comment by luukdv** [comment]
Chose to disable `prefer-template`, so string concatenation is still possible.

**Comment by luukdv** [comment]
We've decided to lint through Webpack (#672) as well.

**Comment by haroldangenent** [comment]
Added `browser: true` and `es6: true` by default.

**Comment by luukdv** [comment]
Works.
