### ISSUE TITLE
Smaller font sizes

### ISSUE THREAD

**Issue by sboerrigter** [trendwerk/trendpress#671]
We've just changed the font sizes to 20px, but I this is a bit too large. I think we should change the font size to 18px like in the latest version of our default styleguide (see attachment). We should then also adjust the heading sizes to match the new text size.

![fontsizes](https://cloud.githubusercontent.com/assets/786875/15934275/463c6aa8-2e63-11e6-924a-5ffcd1163317.png)

**Comment by luukdv** [comment]
Fine by me, maybe we should fix https://github.com/trendwerk/trendpress/issues/631 first.
