### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by luukdv** [trendwerk/trendpress#673]
Should we go with minor releases instead of patches for milestones?

**Comment by haroldangenent** [comment]
I'm not sure. We would probably end up with `1.1.0`, `1.2.0`, `1.34.0`. Maybe we should look into the entire development process and make release cycles shorter for bugs.

After a new minor (e.g. `1.3.0`) we could fix bugs and release `1.3.1` relatively fast. Just one or a small hand of bugs would come into this version. We wouldn't have to wait for a whole release just to fix bugs that way. Minors would contain enhancements and new features.

**Comment by sboerrigter** [comment]
Sounds good to me. Do you also suggest to release minor releases less often?

**Comment by haroldangenent** [comment]
The pressure for a new release would be off, because bugs are fixed in patches. I'd still like as short as possible release cycles for minor releases to keep them simple and manageable. I think we should still try and put as less as possible in a milestone.

**Comment by haroldangenent** [comment]
Closing this, we'll be working as described above.
