### ISSUE TITLE
Trailing non-breaking space

### ISSUE THREAD

**Issue by luukdv** [trendwerk/trendpress#674]
Okay, so I'm just gonna give this a try. ¯\ _ (ツ) _ /¯

Proposal: we should detect if `the_content` ends with one or multiple empty `<p>&nbsp;</p>`'s and remove them.

**Comment by sboerrigter** [comment]
YES!

**Comment by gewoonderrik** [comment]
Why not remove ALL the `<p>&nbsp;</p>`?

**Comment by haroldangenent** [comment]
Maybe an approach like this one. It might be better to strip when saving content, so the editor resembles the website.

https://gist.github.com/Fantikerz/5557617

TrendPress' responsibility or a simple mu-plugin?

**Comment by luukdv** [comment]
Agreed! My vote goes to a mu-plugin.

**Comment by luukdv** [comment]
Also things like `<h2></h2>`.

**Comment by haroldangenent** [comment]
Closing this since it will be a `mu-plugin`.
