### ISSUE TITLE
Remove pagination mid_size

### ISSUE THREAD

**Issue by luukdv** [trendwerk/trendpress#678]
We're defining this at https://github.com/trendwerk/trendpress/blob/master/index.php#L13, but removing it will make no difference since it's explicitly rendered through `pagination.prev` and `pagination.next`.

**Comment by haroldangenent** [comment]
I thought the `mid_size` defined the maximum space between page numbers (so the moment when `...` would be added, when there are a lot of pages). See [`paginate_links`](https://developer.wordpress.org/reference/functions/paginate_links/). Timber performs some computations before passing it, but it seems to be `2` as a default as well.

**Comment by haroldangenent** [comment]
Tried this out, its better with `mid_size` defined. Closing this, feel free to reopen.
