### ISSUE TITLE
Edit telephone number styling

### ISSUE THREAD

**Issue by luukdv** [trendwerk/trendpress#680]
Telephone numbers are converted to links and this doesn't always look good, especially on Edge since it also happens on desktop. We can disable this site-wide:

`<meta name="format-detection" content="telephone=no" />`

What do you guys think?

**Comment by haroldangenent** [comment]
Detecting phone numbers is useful on mobile devices. I've used `x-ms-format-detection="none"` on a phone number before to only disable this on Edge. When using the side-wide format, would phone numbers still be detected on phones / touch devices?

**Comment by luukdv** [comment]
They wouldn't, but if we decide to leave this as is we shouldn't create bug reports about it anymore.

**Comment by haroldangenent** [comment]
I agree.

**Comment by luukdv** [comment]
@sboerrigter @gewoonderrik ?

**Comment by sboerrigter** [comment]
I don't have a strong opinion on this. But if we decide to support clickable phone numbers, I think it should look good.

**Comment by luukdv** [comment]
Changed the title to reflect this. What do you think should be changed?

**Comment by luukdv** [comment]
@sboerrigter do you have any thoughts on this?

**Comment by sboerrigter** [comment]
Can we make telephone numbers look the same as regular links?

**Comment by luukdv** [comment]
I don't think that would be a problem, probably needs some specific styling to overwrite MS/WebKit styles.

**Comment by sboerrigter** [comment]
I’ve looked into this. Here are my findings per OS:

**iOS**
Telephone numbers already look the same as regular links.

**Android**
Telephone numbers are clickable, but look like regular text. Unfortunately it looks like this cannot be changed.

**Windows Phone**
Windows phone makes all clickable telephone numbers blue. The only fix I found for this was to disable telephone number auto detection, which we probably don’t want.

I suggest we just leave this as it is.

**Comment by luukdv** [comment]
Did you test desktops browsers (like Edge) too? If I remember correctly, that's where most of the changes occur.

**Comment by sboerrigter** [comment]
No I didn't test it on desktop, but now I did. Edge behaves the same as Windows Phone. Internet Explorer doesn't auto detect telephone numbers.

I don't agree with the use of clickable links on desktops, but I don't think we should try to fix this if Edge decides to force this behaviour. So I would say wontfix. ok?

**Comment by luukdv** [comment]
Agreed. Let's close.
