### ISSUE TITLE
Gulp: Remove obsolete comments

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#684]
Comments are needed to clarify things. Right now, they don't always do that. We could remove all obsolete comments from `gulpfile.js`.

**Comment by luukdv** [comment]
I think we should keep the main comment for each block, and remove all the inline ones like:

```
// Uglify
.pipe(uglify())
```

**Comment by haroldangenent** [comment]
I chose to remove most comments, because they didn't actually clarify on what was happening. This made the file less readable.

**Comment by luukdv** [comment]
Looks good. Maybe remove this extra whiteline https://github.com/trendwerk/trendpress/blob/c7c0bec12c4a863ee5d2b16ad5246973812f3611/gulpfile.js#L20? Or was it added on purpose?

**Comment by haroldangenent** [comment]
Nope, was an accident.
