### ISSUE TITLE
Refactor _pager.scss

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#687]
Seems a bit illogical right now. Takes time to rewrite this for each website.

**Comment by sboerrigter** [comment]
Can you make the current page and hover state look different? Maybe give the current page a lighter background color?

And we also might want to show less pages on smaller screens (see attached screenshot). Maybe we should only show the previous and next button?

![screen shot 2016-09-29 at 16 55 59](https://cloud.githubusercontent.com/assets/786875/18959230/a58f49b2-8665-11e6-94c2-ba0622f3b2b1.png)

**Comment by haroldangenent** [comment]
> And we also might want to show less pages on smaller screens (see attached screenshot). Maybe we should only show the previous and next button?

Please create a new issue, I didn't change anything about the back-end behaviour.

**Comment by sboerrigter** [comment]
Thanks. Looks better now.

I've created a new issue: https://github.com/trendwerk/trendpress/issues/732
