### ISSUE TITLE
Variable for header height

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#688]
Instead of a `line-height-header`, make a `_dimensions.scss` file that specifies the header height. Could be a map to make it less high on responsive screens.

**Comment by haroldangenent** [comment]
Since I've been rebuilding the entire header a few times lately (for every website), I have decided to give this some priority. The structure is now a bit more logical and how we actually use it in websites.

@luukdv The real big change is the hover state of the menu item: it's not a background anymore (than wouldn't look so nice), but it's a underline. Before you say you hate underlines: this is removed for every website since the menu is mostly very different. Underlines were the simplest thing that could be easily changed.

I have also decided to create a map out of the header height, so smaller screens have a smaller height (instead of re-creating this each time).

**Comment by luukdv** [comment]
@haroldangenent I understand, after all it's just a starter. Seems to work fine!

**Comment by luukdv** [comment]
And +1 for taking my underline hate into consideration 😁
