### ISSUE TITLE
Breakpoints: whole numbers

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#696]
Suggestion:

```
$breakpoints: (
  'small': 421px,
  'medium': 641px,
  'large': 921px,
  'huge': 1281px,
);
```
changes to
```
$breakpoints: (
  'small': 420px,
  'medium': 640px,
  'large': 920px,
  'huge': 1280px,
);
```

**Comment by sboerrigter** [comment]
How will this affect screens that are exactly 640px?

**Comment by haroldangenent** [comment]
It won't. It _will_ affect screens of the exact dimensions of `641px`, but I'm not sure why that extra pixel would matter. The website has to look good on every dimension, after all.

I'm not sure about the exact consequences, but I think the current breakpoints are from a period when only a few screen sizes dominated the market.

**Comment by haroldangenent** [comment]
Decided to use whole numbers.
