### ISSUE TITLE
Rel profile

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#700]
Maybe more of a question, but it this actually necessary? Read some documentation, still not sure what it does.

`<link rel="profile" href="http://gmpg.org/xfn/11">`

http://stackoverflow.com/questions/16636870/what-rel-profile-is-for

**Comment by sboerrigter** [comment]
> In HTML5, the `profile` attribute was dropped.

I guess we can remove it since it is dropped in HTML5

**Comment by haroldangenent** [comment]
Reading on to the next line:

> As an alternative to it, the rel value profile could be used (with several advantages over the profile attribute). RFC 6906 describes the "profile Link Relation Type".

So `rel="profile"` is HTML5's alternative to the `profile` attribute. Not sure yet what it's for though.

**Comment by haroldangenent** [comment]
Decided to drop this, we never use meta data profiles.
