### ISSUE TITLE
Remove comments

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#704]
It would be an option to remove comments to keep the theme simpler. Currently I'm removing comments every time I use TrendPress. Comments could be a starter.

I'm not sure about this though. It's a WordPress theme, shouldn't it include comments?

Opinions please :shipit:

**Comment by luukdv** [comment]
My vote goes to starter.

**Comment by haroldangenent** [comment]
My vote also goes to starter. So starter it is.
