### ISSUE TITLE
Use description lists

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#709]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dt
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dd

For taxonomies and terms (tags in the theme).

**Comment by sboerrigter** [comment]
I've just removed the tags from the theme and I don't see anything else this could apply to. Shall I close this issue?
