### ISSUE TITLE
Placeholder styling

### ISSUE THREAD

**Issue by luukdv** [trendwerk/trendpress#710]
Right now, placeholders are inconsistent across browsers. We should add consistent styling, maybe something like this:

```
::-moz-input-placeholder {
  color: $placeholder;
}

:focus::-moz-input-placeholder {
  color: $placeholder-focus;
}

::-ms-input-placeholder {
  color: $placeholder;
}

:focus::-ms-input-placeholder {
  color: $placeholder-focus;
}

::-webkit-input-placeholder {
  color: $placeholder;
}

:focus::-webkit-input-placeholder {
  color: $placeholder-focus;
}
```

**Comment by luukdv** [comment]
Probably a good idea to do this at the same time as https://github.com/trendwerk/trendpress/issues/525.

**Comment by sboerrigter** [comment]
Why not like this?
```
::-ms-input-placeholder,
::-moz-input-placeholder,
::-webkit-input-placeholder {
  color: $placeholder;

  :focus& {
    color: $placeholder-focus;
  }
}
```

**Comment by luukdv** [comment]
Because it doesn't work.

**Comment by luukdv** [comment]
See https://github.com/trendwerk/trendpress/commit/7ffaa7b3d9ae51bda6f37cd31ff895d54c339866. I didn't want to clutter the `_forms.scss` file so decided to tuck it away in a mixin, although it's technically not a mixin. This way the variables are scoped, which would not be the case if it was a component.
