### ISSUE TITLE
Relative vertical-spacing variable?

### ISSUE THREAD

**Issue by luukdv** [trendwerk/trendpress#715]
Right now, this is a static `40px`. By changing it to `2rem`, it will scale down accordingly. This means `box-link` will have to be changed a bit. Thoughts?

**Comment by sboerrigter** [comment]
I think we should at least use relative elements for margin between text elements (paragraphs, headings, etc..). I think `1em` looks good.

**Comment by haroldangenent** [comment]
Related to https://github.com/trendwerk/trendpress/issues/605, this will probably be removed and heavily refactored.

**Comment by haroldangenent** [comment]
I suggest closing this in favor of #719.
