### ISSUE TITLE
TypeScript

### ISSUE THREAD

**Issue by luukdv** [trendwerk/trendpress#716]
JS is not a typed language, with TS you add optional typing and additional goodies like annotations and decorations. It's gaining a lot of traction in the JS community as of late (Angular, Ionic, ReactiveX etc). What do you guys think, should we consider adding it to our workflow?

**Comment by haroldangenent** [comment]
Not sure. This might be an overkill, given the simplicity of our JavaScript. We'll probably don't need annotations and decorations for this.

**Comment by luukdv** [comment]
@gewoonderrik @sboerrigter?

**Comment by sboerrigter** [comment]
I don't use Javascript enough to have a good opinion on this. I think you guys should decide.

**Comment by luukdv** [comment]
Closing this for now.
