### ISSUE TITLE
Introduce `$image-margin` in `_align.scss`

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#726]
40px is duplicated a lot.

**Comment by sboerrigter** [comment]
Why did you use `&.alignleft` instead of putting `.alignleft` below the previous declaration? I think the second option is more logical an readable.

**Comment by haroldangenent** [comment]
To get a shared scope where the variable `$image-margin` could live in (since it's a local variable, it needs a specific scope, otherwise it could conflicts when developing a website).
