### ISSUE TITLE
Improve pager on smaller screens

### ISSUE THREAD

**Issue by sboerrigter** [trendwerk/trendpress#732]
We might want to show less pages on smaller screens (see attached screenshot). Maybe we should only show the previous and next button?

![screen shot 2016-09-29 at 16 55 59](https://cloud.githubusercontent.com/assets/786875/18961439/5f7ab076-866d-11e6-9269-3f7d5b100737.png)

**Comment by sboerrigter** [comment]
We could also remove line 35 to 50 from `_pager.scss`. What do you guys think?

https://github.com/trendwerk/trendpress/blob/master/assets/styles/components/_pager.scss#L35-L50

**Comment by luukdv** [comment]
About the commit: looks good, but is done really 'early' regarding breakpoints. On screens ±800px wide they can be shown right?

About https://github.com/trendwerk/trendpress/issues/732#issuecomment-256619407: think it looks better grouped together. By the way, `none` is not a valid value for margins.
