### ISSUE TITLE
Use relative margin for buttons?

### ISSUE THREAD

**Issue by sboerrigter** [trendwerk/trendpress#733]
`1em` instead of `20px`?

**Comment by sboerrigter** [comment]
@haroldangenent @luukdv what's your opinion on this?

**Comment by luukdv** [comment]
I think `1em` is not enough on smaller screens, although it doesn't make _that_ much of a difference. 20px seems like a fine value in all cases. Why would you want this to be relative?

**Comment by sboerrigter** [comment]
For better vertical rythm. If we use `1em` or `2em` for line-heights and (bottom) margins everything will look consistent and better aligned.

**Comment by sboerrigter** [comment]
We are probably going to remove button margin.
