### ISSUE TITLE
Last elements in content

### ISSUE THREAD

**Issue by luukdv** [trendwerk/trendpress#735]
Right now, we have this for posts: https://github.com/trendwerk/trendpress/blob/master/assets/styles/components/_post.scss#L14. We should also add this for pages to be consistent.

**Comment by sboerrigter** [comment]
What if the last element is not a `<p>` but something else (like a `<ul>` or `<span>`)? Maybe we should not remove the margin of the last element, but decrease the margin of the container (#731).

**Comment by haroldangenent** [comment]
:+1: for @luukdv's suggestion. I think each element should be self-containing.

**Comment by sboerrigter** [comment]
`.post` is only used for archives. This code doesn't apply to singular posts and pages. We could add it to `main .wrapper`, but I don't think this is a good idea. It doesn't look good if there are other elements on the page. 

Example:

![screen shot 2016-10-27 at 13 03 03](https://cloud.githubusercontent.com/assets/786875/19764883/be103e7e-9c45-11e6-981e-26113f840a3f.png)

**Comment by luukdv** [comment]
Thanks for the clarification, assumed this was for singles. `main .wrapper` seems like a good idea. The reason it sometimes doesn't look good is because of `p:last-of-type` I think, we could change this to `p:last-child`.

**Comment by sboerrigter** [comment]
See https://github.com/trendwerk/trendpress/commit/ca407963da171c73863a69f37806411556bbe7d9

**Comment by luukdv** [comment]
Epic.
