### ISSUE TITLE
Remove .read-more from Admin\Editor

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#738]
Seems to be removed on every website. Maybe remove secondary button as well and just keep a "button" that admins can use.

**Comment by luukdv** [comment]
Did you remove the related styling as well?

**Comment by luukdv** [comment]
Did you remove the read-more styling as well?

**Comment by sboerrigter** [comment]
No, because they are also used on the posts archive (and maybe some other places as well).
