### ISSUE TITLE
TinyMCE style select box styling

### ISSUE THREAD

**Issue by sboerrigter** [trendwerk/trendpress#744]
I think the TinyMCE style select box should look the same as the format select box. Can we fix this?

![screen shot 2016-10-27 at 13 21 16](https://cloud.githubusercontent.com/assets/786875/19765380/53cf9e80-9c48-11e6-985f-7e9f80bf1bd9.png)

**Comment by luukdv** [comment]
I don't think we should we should put effort to the out-of-the-box TinyMCE implementation, since we would have to review it after each release. Not worth the time in my opinion. Besides, this is not a TrendPress bug right?

**Comment by haroldangenent** [comment]
👍  @luukdv.

This does not seem like a responsibility of a theme. If this is important to you, you should look for existing issues in WordPress trac or create a new one.
