### ISSUE TITLE
Remove support for two buttons next to eachother in the editor

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/trendpress#747]
Removing support for this would mean:
- Button's don't need `inline-block`
- Button's don't need margin by default

**Comment by haroldangenent** [comment]
@luukdv It seems buttons still need `inline-block` for other editor-specific behaviour (text falling next to the button if it would `float`). 😞 

Could you double-check?

**Comment by luukdv** [comment]
Ah yes, of course. Too bad. Double-checked, looks good.
