### ISSUE TITLE
Globally add .border-box();

### ISSUE THREAD

**Issue by sboerrigter** [trendwerk/trendpress#94]
We use a LESS mixin .border-box(); to define the width and height of elements including the padding and border radius. See: http://css-tricks.com/box-sizing/

Isn't it an idea to add this globally on all elements? I don't see why you wouldn't want to use this. This shortens the code.

**Comment by haroldangenent** [comment]
Digging this one up from ancient history. I think we should add this now.

**Comment by luukdv** [comment]
Agreed!

```
* {
  box-sizing: border-box;
}
```

**Comment by gewoonderrik** [comment]
Global `box-sizing: border-box;` has been added. Used *Universal Box Sizing with Inheritance* as mentioned [here](https://css-tricks.com/box-sizing/) because it seemed like the most flexible solution. Please review!

**Comment by haroldangenent** [comment]
Some feedback:

- Can the `border-box` declaration be removed from existing selectors?
- Why did you choose to use `content-box` for the search icon, instead of increasing it's size to conform to the `border-box` default?

**Comment by gewoonderrik** [comment]
I've removed the double declarations.

Increasing size seemed a bit of a hack to me. Just overwriting the default `box-sizing` values seemed more logical.
